npocccties/chibichilo

- .vscode/settings.json
required: esbenp.prettier-vscode
resolved: #38
> Add VSCode formatter settings

- components/atoms/InputLabel.stories.tsx
- components/atoms/RequiredDot.stories.tsx
- components/atoms/RequiredDot.tsx
- components/atoms/TextField.stories.tsx
- components/atoms/TextField.tsx
- components/organisms/BookEditDialog.stories.tsx
- components/organisms/BookEditDialog.tsx
- components/organisms/BookForm.tsx
- components/organisms/TopicEditDialog.stories.tsx
- components/organisms/TopicEditDialog.tsx
- components/organisms/TopicForm.tsx
- styles/container.ts
- styles/dialogContent.ts
- styles/inputLabel.ts
作成と編集は単一のコンポーネントで、propsで挙動を変えるようにしたいかなと作りながら思いました
あわせてTextFieldのrequiredのスタイルを更新するなどしています
> {ブック,トピック}{作成,編集}UIコンポーネントの追加

- package.json
- yarn.lock
> chore: upgrade storybook to 6.1.1

- server/config/app.ts
See also https://github.com/fastify/fastify-swagger#integration
> feat: CSP対応

- server/models/book.ts
- server/models/book/section.ts
- server/models/resource.ts
- server/models/topic.ts
- server/models/user.ts
- server/models/videoResource.ts
- server/types/fastifySession.ts
- server/utils/book.ts
- server/utils/bookToBookSchema.ts
- server/utils/session.ts
- server/utils/topicToTopicSchema.ts
- server/utils/user.ts
- tsconfig.json
> chore: s/\$prisma/@prisma/g

- .github/ISSUE_TEMPLATE/100-bug-report-ja.md
- .github/ISSUE_TEMPLATE/200-bug_report-en.md
labelsを使えばprefixを付けずとも済むと思った﻿のでそうしました
> Issueタイトルに`[BUG]` prefixではなくラベルを使う

- .storybook/main.js
- package.json
globを使って書き直してみました
書き直してみましたが、あまりよみやすくない気持ちもあってどうしようかなとおもってましたが、とりあえずPRにしてみました
> chore: storybook の main.js の整理

- samples/resource.ts
#103 でコンフリクトを解消する際に考慮できておらずサンプルデータが一部古かったので新しいものを反映しました
> fix: samples

- components/organisms/BookForm.stories.tsx
- components/organisms/BookForm.tsx
- components/templates/BookNew.stories.tsx
- components/templates/BookNew.tsx
- package.json
- samples/book.ts
- server/prisma/schema.prisma
- types/book.ts
- yarn.lock
#96 関連
まずBookFormにonSubmitを注入する部分だけ
- react-hook-form の導入
> feat: support onSubmit in BookForm Component

- components/atoms/CourseChip.stories.tsx
- components/atoms/CourseChip.tsx
- components/organisms/BookAccordion.tsx
- components/organisms/BookForm.tsx
- components/organisms/BookPreview.tsx
- components/organisms/TopicForm.tsx
- components/templates/Book.tsx
- components/templates/BookEdit.tsx
- components/templates/BookImport.tsx
- components/templates/BookLink.tsx
- components/templates/BookNew.tsx
- components/templates/BookUnknown.tsx
- components/templates/Books.tsx
- components/templates/TopicEdit.tsx
- components/templates/TopicNew.tsx
- pages/_app.tsx
- AppBarをtemplatesで読むのではなく_app.tsxで読むようにしました
- CourseChipでコース名が配置されていた箇所にコースidが入るようにしたり、ホバー時にコース名が出るようにしました
> AppBarをpages/_app.tsxで読むように&CourceChipの更新

- components/organisms/BookForm.tsx
- components/templates/Book.stories.tsx
- components/templates/Book.tsx
- components/templates/BookNew.stories.tsx
- components/templates/BookNew.tsx
- components/templates/Books.stories.tsx
- components/templates/Books.tsx
- openapi/models/InlineObject2.ts
- openapi/models/InlineObject3.ts
- openapi/models/InlineResponse2001Books.ts
- pages/book/new.tsx
- pages/books.tsx
- samples/book.ts
- server/config/seeds/books.ts
- server/models/book.ts
- server/package.json
- server/prisma/migrations/20201221085703_init/migration.sql
- server/prisma/schema.prisma
- server/utils/book/createBook.ts
- server/utils/book/updateBook.ts
resolved: #96
- fix: rename abstract to description
- fix: セクションが空の時エラーになる問題への対処
- sectionsがnullならば[]として作成時扱う
- bookをnullとundefinedを同一視する
- feat: ブック作成画面の作成
- feat: onBookNewClick実装/注入
> feat book new

- components/templates/BookUnknown.tsx
- pages/index.tsx
> feat: 学習者がブックと連携されていないLTIリンクからアクセスした際エラー画面を表示

- pages/books.tsx
戻るボタンで戻れないのは不便だなと思った
(誤ってrouter.replaceを使っていた)
> fix: マイブック画面に戻れない問題の修正 (replace → push)

- server/prisma/seed.ts
- server/utils/topic/resourceConnectOrCreateInput.ts
- server/utils/topic/topicCreateInput.ts
- server/utils/topic/upsertTopic.ts
- fix: server/utils/topic/upsertTopic リソース作成強制しない
- fix: seed 失敗時は異常終了させて知らせる
関連: https://github.com/npocccties/ChibiCHiLO/issues/130#issuecomment-750838817
> fix upsert topic error

- components/organisms/TopicPreview.stories.tsx
- components/organisms/TopicPreview.tsx
- components/templates/TopicImport.stories.tsx
- components/templates/TopicImport.tsx
> トピックインポート画面のUI実装

- components/atoms/AppBarNavButton.stories.tsx
- components/atoms/AppBarNavButton.tsx
- components/atoms/Item.tsx
- components/organisms/AppBar.stories.tsx
- components/organisms/AppBar.tsx
- components/organisms/BookItemDialog.tsx
- components/organisms/LtiItemDialog.stories.tsx
- components/organisms/LtiItemDialog.tsx
- pages/_app.tsx
- samples/index.ts
- samples/session.ts
- utils/session.ts
> AppBarのナビゲーション、LTI情報ダイアログ等の実装

- components/molecules/TopicViewerContent.tsx
- components/organisms/TopicPreview.stories.tsx
- components/organisms/TopicPreview.tsx
- components/templates/BookEdit.stories.tsx
- components/templates/BookEdit.tsx
- components/templates/TopicImport.stories.tsx
- components/templates/TopicImport.tsx
- pages/book/edit.tsx
- pages/book/topic/edit.tsx
- pages/book/topic/import.tsx
- utils/topic.ts
- utils/topicCreateBy.ts
- utils/topics.ts
> feat: トピックインポート画面実装

- pages/index.tsx
> feat: 連携済みならばそのブックに遷移

- components/atoms/CourseChip.tsx
- components/templates/BookLink.stories.tsx
- components/templates/Books.stories.tsx
- openapi/apis/DefaultApi.ts
- openapi/models/InlineObject.ts
- openapi/models/InlineResponse200.ts
- openapi/models/InlineResponse2006LtiLaunchBody.ts
- pages/link.tsx
- samples/ltiResourceLink.ts
- samples/session.ts
- server/config/seeds/ltiResourceLinks.ts
- server/models/ltiResourceLink.ts
- server/prisma/migrations/20210208051950_add_lti_context_label/migration.sql
- server/prisma/schema.prisma
- server/utils/ltiResourceLink.ts
- server/validators/ltiLaunchBody.ts
> feat: context_labelを使う

- components/organisms/BookChildren.stories.tsx
- components/organisms/BookChildren.tsx
- components/templates/Book.tsx
close #175
再生中のトピックにprimary[50]の色がつくようにしました
> feat: BookChildrenで再生中のトピックが分かるように

- components/organisms/TopicForm.tsx
- utils/videoResource.ts
> feat: Blur後に入力した動画urlでプレビューできるように

- components/organisms/TopicForm.tsx
- package.json
- yarn.lock
#205 でBlurイベントでフックしていたものを、Changeイベントにuse-debounceを使って入力後プレビューに反映されるようにしました
> feat: Blurではなく入力後プレビューに反映されるように

- components/organisms/Video/Vimeo.tsx
> fix: Vimeoコンポーネントを再マウントするとプレイヤーが表示されない問題の修正

- .storybook/preview.tsx
- components/organisms/Problem.stories.tsx
- components/organisms/TopicForm.stories.tsx
- components/templates/Book.stories.tsx
- components/templates/TopicEdit.stories.tsx
- components/templates/TopicNew.stories.tsx
[CSF](https://storybook.js.org/docs/react/api/csf)に対応。
/?path=/story/templates-book--default 等が問題なく表示できることを確認。
[パラメーター](https://storybook.js.org/docs/react/writing-stories/parameters)﻿ には対応せずそのままです。
> feat: Component Story Format (CSF) 

- server/config/roles.ts
[Blackboard でコース作成者 (COURSE_BUILDER) にあたる LISコンテキストロールでいうContentDeveloper](https://help.blackboard.com/ja-jp/Learn/Administrator/SaaS/Integrations/Learning_Tools_Interoperability#lti_OTP-7)﻿をサポート
> feat: add urn:lti:role:ims/lis/ContentDeveloper

- components/organisms/Video/VimeoPlayer.tsx
> fix: Vimeo動画が閲覧ページ以外で自動再生される問題の修正

- components/organisms/TopicPreview.stories.tsx
- components/organisms/TopicPreview.tsx
- components/templates/TopicImport.tsx
- components/templates/Topics.tsx
- utils/topics.ts
- utils/userTopics.ts
> feat: TopicPreviewのUIを小さめに

- components/organisms/BookForm.tsx
- components/organisms/TopicForm.tsx
- components/templates/BookEdit.stories.tsx
- components/templates/BookEdit.tsx
- components/templates/BookNew.stories.tsx
- components/templates/BookNew.tsx
- components/templates/TopicEdit.stories.tsx
- components/templates/TopicEdit.tsx
- components/templates/TopicNew.tsx
- pages/book/edit/index.tsx
- pages/book/edit/topic/generate.tsx
- pages/book/generate.tsx
- pages/book/import/index.tsx
- pages/book/index.tsx
- pages/book/new.tsx
- pages/book/topic/generate.tsx
- pages/book/topic/import/index.tsx
- pages/link.tsx
- pages/topics/generate.tsx
- pages/topics/index.tsx
- pages/topics/new.tsx
- server/models/book.ts
- server/utils/eventLogger.ts
- utils/book.ts
- utils/useBookNewHandlers.ts
- utils/useTopicNewHandlers.ts
close #220
- fix: use camel case
- feat: generate endpoint
- feat: 自身以外が作成したブックとそのブック内のトピックを複製せずリンク
> feat: 自身以外が作成したブックとそのブック内のトピックを複製せずリンク

- components/organisms/BookChildren.stories.tsx
- components/organisms/BookChildren.tsx
- components/templates/Book.stories.tsx
- components/templates/Book.tsx
- components/templates/BookNew.stories.tsx
- components/templates/BookNew.tsx
- components/templates/TopicNew.stories.tsx
- components/templates/TopicNew.tsx
- pages/book/index.tsx
- store/session.ts
- utils/session.ts
close #235
- refactor: updateSessionAtom
- feat: 編集権限に応じたブック閲覧での編集ボタン非表示
- feat: フォークすることを利用者に通知
> feat: 編集権限に応じたブック閲覧画面での編集ボタンの非表示/フォークすることを利用者に通知

- utils/eventLogger/playerTracker.ts
> fix: trackchange イベントが意図せず発火する問題の修正

- components/organisms/BookChildren.tsx
> fix: 閲覧画面のセクション・トピックの通し番号の修正

- components/organisms/CollapsibleContent.stories.tsx
- components/organisms/CollapsibleContent.tsx
- components/templates/BookEdit.tsx
> feat: ブック編集の並びをブック内容を上に&ブック内容を折りたたむように

- components/atoms/SharedIndicator.tsx
- components/organisms/BookForm.tsx
- components/organisms/TopicForm.tsx
- server/prisma/schema.prisma
> feat: 文言変更: 共有→シェア

- components/organisms/ActionHeader.tsx
- components/templates/Book.stories.tsx
- components/templates/Book.tsx
- components/templates/Topics.stories.tsx
> feat: ブック閲覧画面でブック名を固定表示するように

- components/organisms/ActionHeader.tsx
- components/templates/Book.stories.tsx
教員権限であればAppBarを考慮し、そうでなければAppBarを考慮しないようにしました
fix #301
> fix: 学習者がブックを閲覧した際、タイトルバーより上に空白が生じる

- components/molecules/DraggableBookChildren.tsx
- components/organisms/BookEditChildren.tsx
#268 に関連しています
セクションをドラッグするのか、トピックをドラッグするかについて、セクション用のドラッグのつまみを追加することで改善を試みています
> feat: セクションのドラッグ用のつまみ

- components/molecules/TopicViewerContent.tsx
- components/organisms/BookItemDialog.tsx
> feat: TopicViewerとBookItemDialogの解説以外の項目の文字を小さく

- components/atoms/SortSelect.stories.tsx
- components/atoms/SortSelect.tsx
> feat: onSortChangeイベント

- components/atoms/CreatorFilter.stories.tsx
- components/atoms/CreatorFilter.tsx
- components/templates/BookImport.tsx
- components/templates/BookLink.tsx
- components/templates/Books.tsx
- components/templates/TopicImport.tsx
- components/templates/Topics.tsx
#297 の自分と自分以外の作成者でのフィルタリングに使うUIコンポーネントです
> feat: CreatorFilterコンポーネント

- components/atoms/CreatorFilter.tsx
https://github.com/npocccties/ChibiCHiLO/pull/331#discussion_r597533474 の対応です
> refactor: CreatorFilterでstate管理しない

- components/atoms/SortSelect.tsx
- components/templates/BookImport.tsx
- components/templates/BookLink.tsx
- components/templates/Books.tsx
- components/templates/TopicImport.tsx
- components/templates/Topics.tsx
- pages/book/import/index.tsx
- pages/book/topic/import/index.tsx
- pages/books/index.tsx
- pages/link.tsx
- utils/books.ts
- utils/topics.ts
- utils/useSortOrder.ts
- utils/userBooks.ts
- utils/userTopics.ts
close #140
feat: 一覧の並び順の切り替え機能の有効化
- ブックの再利用
- マイブック
- トピックの再利用
- マイトピック
- ブックの提供
- SortSelect: イベントハンドリングの不具合の修正
> feat: 一覧の並び順の切り替え機能のサポート

- .storybook/main.js
- package.json
- yarn.lock
docs: https://github.com/storybookjs/storybook/tree/v6.1.21/addons/a11y#readme﻿
> chore: @storybook/addon-a11y のインストール - アクセシビリティの改善のための検査目的

- INSTALL-ja.md
```diff
-成功すると CSV ファイル `public/LICENSE.csv` が得られます。
+成功するとテキストファイル `public/LICENSE` が得られます。
```
> docs: fix filename

- components/templates/BookImport.tsx
> fix: ブックの再利用でトピックが追加されない問題の対処

- components/atoms/AppBarNavButton.stories.tsx
- components/atoms/CreatorFilter.tsx
- components/organisms/AppBar.tsx
- components/templates/BookImport.tsx
- components/templates/BookLink.tsx
- components/templates/Books.tsx
- components/templates/TopicImport.tsx
- components/templates/Topics.tsx
- pages/book/import/index.tsx
- pages/book/topic/import/index.tsx
- pages/books/index.tsx
- pages/link.tsx
- pages/topics/index.tsx
- types/filter.ts
- utils/books.ts
- utils/topics.ts
- utils/useBooks.ts
- utils/useFilter.ts
- utils/useTopics.ts
- utils/userBooks.ts
- utils/userTopics.ts
close #183, close #297
- feat: すべての作成者のブックの一覧とトピックの一覧のサポート
- feat: 作成者のフィルタリングのサポート
- ブックの提供
- ブックの再利用
- トピックの再利用
- ブック一覧
- トピック一覧
> feat: すべての作成者のブックの一覧とトピックの一覧/作成者のフィルタリングのサポート

- .eslintrc.yml
- components/atoms/CourseChip.tsx
- components/atoms/SearchTextField.stories.tsx
- components/atoms/SearchTextField.tsx
- components/molecules/BookTree.tsx
- components/organisms/BookAccordion.tsx
- components/organisms/BookPreview.tsx
- components/templates/BookImport.tsx
- components/templates/BookLink.tsx
- components/templates/Books.tsx
- components/templates/TopicImport.tsx
- components/templates/Topics.tsx
- jest.config.js
- package.json
- server/.eslintrc.yml
- store/search.ts
- utils/search/bookSearch.test.ts
- utils/search/bookSearch.ts
- utils/search/parse.test.ts
- utils/search/parse.ts
- utils/search/query.ts
- utils/search/stringify.test.ts
- utils/search/stringify.ts
- utils/search/topicSearch.test.ts
- utils/search/topicSearch.ts
- utils/useBooks.ts
- utils/useTopics.ts
close #141
- chore: install jest
- feat: 検索クエリーによるフィルタリングのサポート
> feat: 検索クエリーによるフィルタリングのサポート

- pages/books/index.tsx
- pages/topics/generate.tsx
- pages/topics/index.tsx
> fix: ブック一覧から自身以外の作成したブックの編集画面にアクセスできる不具合の修正

- server/utils/getValidUrl.ts
- server/utils/videoResource.ts
- utils/eventLogger/getFilePath.test.ts
- utils/eventLogger/getFilePath.ts
- utils/eventLogger/logger.ts
- utils/getValidUrl.ts
> fix: URLの取得に失敗したときビデオ切り替え等に失敗する不具合への対処

- components/organisms/Video/VideoJs.tsx
- components/organisms/Video/Vimeo.tsx
- store/playerTracker.ts
- utils/eventLogger/playerTracker.ts
> fix: Vimeoの動画URLの取得に失敗しうる問題への対処

- ARCHITECTURE.md
- CONTRIBUTING-ja.md
- INSTALL-ja.md
- README-en.md
- README-ja.md
- README.md
- components/organisms/ActionHeader.tsx
- components/organisms/AppBar.tsx
- components/organisms/Video/YouTubePlayer.tsx
- package.json
- pages/_app.tsx
- server/README.md
- server/package.json
> fix: "CHiBi-CHiLO" への用語の統一

- utils/activity.ts
> fix: 学習者以外の学習活動を記録しない

- pages/book/import/index.tsx
- pages/book/topic/import/index.tsx
- utils/topic.ts
再利用の時点で複製されると同じトピックが増えすぎることを懸念したので対応．
今後複製か参照か選択できるような仕組みがあれば良い．
Co-authored-by: Kimiaki Kuno <knokmki612@users.noreply.github.com>
Co-authored-by: YABUKI Yukiharu <yabuki@netfort.gr.jp>
> feat: #386 トピック再利用時は複製ではなくリンクにする

- components/atoms/Typography.stories.tsx
- components/organisms/BookEditChildren.tsx
- components/templates/BookEdit.tsx
> feat: ブック編集画面「トピック順」という文言を使う

- pages/books/index.tsx
ハンドラーの記述が適切でありませんでした。 fix #420
> fix: ブック一覧のもっと詳しくをクリックしても反応しない

- components/organisms/BookChildren.tsx
- components/templates/Book.tsx
- pages/books/index.tsx
> feat: ブック一覧上のブック視聴ダイアログから編集の動線を取り除く

- components/organisms/BookPreview.tsx
- components/organisms/TopicPreview.tsx
- package.json
- yarn.lock
> feat: 一覧の動画プレイヤーはViewport周辺時のみ描画されるように

- components/molecules/BookChildrenTree.tsx
close #152 
importの記述をミスしていました
> fix: アイコンが意図した表示になっていない

- components/atoms/DescriptionList.tsx
- components/molecules/TopicViewerContent.tsx
- components/organisms/BookForm.tsx
- components/organisms/BookInfo.tsx
- components/organisms/CollapsibleContent.tsx
- components/templates/Book.tsx
- components/templates/BookEdit.tsx
resolve #432 
iPad相当(1024x768)の画面領域で検証しました
before
after
> feat: ブック視聴画面上部の表示領域が縮減するようなレイアウト調整 

- components/organisms/BookForm.stories.tsx
- components/organisms/BookForm.tsx
- components/organisms/TopicForm.stories.tsx
- components/organisms/TopicForm.tsx
- components/templates/BookEdit.tsx
- components/templates/BookNew.tsx
- components/templates/TopicEdit.tsx
- components/templates/TopicNew.tsx
- pages/book/edit/index.tsx
- types/bookPropsWithSubmitOptions.ts
- utils/useBookLinkHandler.ts
- utils/useBookNewHandlers.ts
> feat: ブック作成編集時に提供もおこなうオプション

- components/templates/Books.tsx
> feat: 提供中のブックでは提供しているリンクを表示しない

- components/atoms/BookChildrenItem.stories.tsx
- components/atoms/BookChildrenItem.tsx
- components/organisms/BookChildren.stories.tsx
- components/organisms/BookChildren.tsx
- components/templates/Book.tsx
#410 への対応です
> 
> セクションがおせるのかどうか、おしたらどうなるのか、おせないのであればどのようにおせないことを提示するのかは、引き続き実装しながら検討したいと思います
> 
> _Originally posted by @knokmki612 in https://github.com/npocccties/chibichilo/issues/410#issuecomment-871212741_
セクションを押した場合は、セクション内の最初のトピックに切り替える挙動にしました
> feat: ツリー表示風のセクションリスト

- components/molecules/TopicViewerContent.tsx
- components/organisms/BookChildren.tsx
- components/organisms/BookInfo.tsx
- utils/formatInterval.test.ts
- utils/formatInterval.ts
> feat: 学習時間をトピック名とともに表示する 

- components/organisms/TopicViewer.tsx
> feat: 動画切り替え時に先頭から再生する

- openapi/models/InlineObject1.ts
- openapi/models/InlineResponse2001AuthorSettings.ts
- server/validators/userSettings.ts
間違っていたら申し訳ないのですがおそらく使われていないパラメーターが存在しており整理したいと考えました。削除してよいでしょうか? > @hATrayflood
> fix: 使われていない zoomImportAutodelete パラメーターの削除

- .github/workflows/build.yml
> chore: actions/setup-node@v2 使う

- .github/workflows/build.yml
- .gitignore
- package.json
- ESLintキャッシュ有効化
- lint:report と lint:fix を統合
> perf: ESLintキャッシュ有効化とCIでの実行回数の削減

- ARCHITECTURE.md
- README.md
- app.json
- package.json
- server/package.json
Herokuへのデプロイを可能にする対応
(デプロイ後RDBのマイグレーションとLMSの設定を実施してください)
> feat: support heroku

- components/organisms/AuthorsInput.tsx
- components/organisms/BookForm.tsx
- components/organisms/KeywordsInput.stories.tsx
- components/organisms/KeywordsInput.tsx
- components/organisms/TopicForm.tsx
- utils/useKeywordsInput.ts
resolve #570 #568 #567 #566
確認したこと
- ブック編集画面でキーワードを追加できること
- トピック編集画面でキーワードを追加できること
- ブック編集画面でキーワードを削除できること
- トピック編集画面でキーワードを削除できること
> feat: キーワード入力欄

- components/organisms/ContentPreview.tsx
- components/templates/BooksImport.tsx
- components/templates/TopicImport.tsx
- components/templates/Topics.tsx
トピック一覧でキーワードをクリックしても反応しなかったためブック一覧と同じ振る舞いに修正
> fix: handleKeywordClick

- server/prisma/schema.prisma
キーワードには "," が含まれうるためそのようにコメントを更新
> docs: キーワードには "," が含まれうるためそのようにコメントを更新

- components/organisms/SearchPagination.tsx
- store/search.ts
- utils/useBooks.ts
- utils/useTopics.ts
一覧画面にて意図しないページが表示されうる問題の修正
検索クエリーが更新されるとページが先頭にリセットされるように変更しました
> fix: 一覧画面にて意図しないページが表示されうる問題の修正

- server/prisma/migrations/20211124170332_set_keyword_zoom/migration.sql
- server/utils/zoom/import.ts
> feat: Zoomインポートへのキーワード付与と移行

- components/atoms/License.tsx
- components/organisms/TopicViewerContent.tsx
- components/organisms/Video/VideoPlayer.tsx
- components/organisms/Video/index.tsx
- utils/licenses.ts
> ライセンス表示/入力の調整, etc.

- components/organisms/SearchPagination.tsx
- components/templates/BookImport.stories.tsx
- components/templates/BookImport.tsx
- components/templates/Books.stories.tsx
- components/templates/Books.tsx
- components/templates/TopicImport.stories.tsx
- components/templates/TopicImport.tsx
- components/templates/Topics.stories.tsx
- components/templates/Topics.tsx
- openapi/models/InlineResponse2001.ts
- openapi/models/InlineResponse2001Books.ts
- server/models/search.ts
- server/services/search.ts
- server/utils/search/bookSearch.ts
- server/utils/search/search.ts
- server/utils/search/topicSearch.ts
- utils/useContents.ts
resolved #559
- refactor: SearchResultSchema として外部化
- feat: 検索の該当件数の集計と表示の実装
> feat: 検索の該当件数の集計と表示の実装

- components/organisms/TopicForm.tsx
- components/organisms/TopicPreviewDialog.tsx
- components/organisms/TopicViewer.tsx
- components/organisms/TopicViewerContent.tsx
- components/organisms/Video.stories.tsx
- components/organisms/Video/VideoResource.tsx
- components/organisms/Video/index.tsx
関連: #553
TopicViewerでupdateVideoを呼び出したのち
TopicViewerContentを含むコンポーネントを表示した場合
特定のブックに含まれるトピックしか表示されなくなることが原因
> fix: トピックプレビューが表示されない

- utils/licenses.ts
> fix: CCライセンスの並びが制約の強さの昇順になっていない

- server/utils/search/bookSearch.ts
- server/utils/search/topicSearch.ts
関連: #606
確認したこと:
- 開発用サーバーにてトピック名に Unicode 13 CaseFolding.txt に含まれる文字を含め区別されず検索可能なこと
- SQL `LIKE` 演算子が `ILIKE` 演算子に変更されていること
参考文献:
- [Case sensitivity \(Reference\) \| Prisma Docs](https://www.prisma.io/docs/concepts/components/prisma-client/case-sensitivity)
- [PostgreSQL: Documentation: 13: 9\.7\. Pattern Matching](https://www.postgresql.org/docs/13/functions-matching.html)
- http://www.unicode.org/Public/UCD/latest/ucd/CaseFolding.txt
> feat: 検索時にアルファベットの大文字小文字の区別させない

- components/atoms/AuthorFilter.stories.tsx
- components/atoms/AuthorFilter.tsx
- components/atoms/CourseChip.tsx
- components/atoms/SharedFilter.stories.tsx
- components/atoms/SharedFilter.tsx
- components/organisms/FilterColumn.stories.tsx
- components/organisms/FilterColumn.tsx
- components/templates/BookImport.tsx
- components/templates/Books.tsx
- components/templates/TopicImport.tsx
- components/templates/Topics.tsx
- package.json
- server/models/searchQuery.ts
- store/search.ts
- types/sharedFilter.ts
> feat: 絞り込みカラム

- server/utils/search/bookSearch.ts
- server/utils/search/createScopes.test.ts
- server/utils/search/createScopes.ts
- server/utils/search/topicSearch.ts
関連: https://github.com/npocccties/chibichilo/issues/631
> 「著者：すべて，共有：なし」にすると，なにも表示されなくなります．
この問題の修正です。
> fix: 「著者:すべて」かつ「共有:なし」のときヒットしない問題の修正

- components/organisms/Search.stories.tsx
- components/organisms/Search.tsx
- components/templates/BookImport.tsx
- components/templates/Books.tsx
- components/templates/TopicImport.tsx
- components/templates/Topics.tsx
- package.json
- store/search.ts
- types/searchTarget.ts
> feat: 検索対象の選択可能な検索

- components/atoms/License.tsx
- components/organisms/ContentPreview.tsx
> feat: ライセンスはリンクへの動線を提供しない, etc.

- components/templates/Topics.tsx
> feat: 自分が作成者ではないコンテンツはシェア・削除を操作不可能に

- components/atoms/CourseChip.tsx
- components/atoms/KeywordChip.tsx
関連: #629 
動作例
https://user-images.githubusercontent.com/9744580/151742293-a93dd068-75c6-4aa7-ae99-a1cb78061eda.mp4
> feat: Chip類にTooltipで補助テキストを表示するように

- pages/book/edit/index.tsx
- server/utils/book/updateBook.ts
> fix: セクションへの意図した変更が行われない問題の修正

- components/templates/BookEdit.tsx
> fix: duplicate book edit forms

- components/organisms/Video/VideoResource.tsx
> fix: トピックプレビューが表示されない問題の修正

- components/molecules/VideoEditor.stories.tsx
- components/molecules/VideoEditor.tsx
- components/organisms/TopicForm.tsx
- utils/video/usePaused.ts
関連: #715
デモ: https://chibi-ch-i-lo-git-feat-pause-ties-makimura.vercel.app/storybook/iframe.html?id=templates-topicedit--default
> feat: 再生/一時停止ボタンの実装

- components/molecules/VideoEditor.tsx
- components/organisms/TopicForm.tsx
関連: #717
デモ: https://chibi-ch-i-lo-git-feat-new-topic-edit-ties-makimura.vercel.app/storybook/iframe.html?id=templates-topicedit--default&args=&viewMode=story
> feat: トピック編集ページのいくつかの項目を隠す

- components/organisms/TopicForm.tsx
- components/organisms/TopicForm/TimeRequiredInputControl.tsx
- package.json
- yarn.lock
ref. #719
デモ: https://chibi-ch-i-lo-git-feat-alert-time-required-ties-makimura.vercel.app/storybook/iframe.html?id=templates-topicedit--default&args=&viewMode=story
> feat: 保存されている学習時間が変更された場合通知を行う

- utils/getLocaleListString.ts
#705 対応．将来的には，今回行った utils/getLocaleListString.ts の変更を，https://github.com/npocccties/chibichilo/commit/b3ba747f12c5d4fdad7edff87511f157425cf86c に戻す．
> fix: macOS Catalinaでアクセスできない問題の修正

- server/utils/author/insertAuthors.ts
- utils/useAuthorsHandler.ts
ref https://github.com/npocccties/chibichilo/issues/692
> fix: コンテンツ作成画面で本人を表示する対応

- components/organisms/BookPreviewDialog.tsx
- components/organisms/TopicForm.tsx
- components/organisms/Video/VideoResource.tsx
- components/organisms/Video/index.tsx
- pages/books/index.tsx
> Fix book preview

- components/organisms/Video/index.tsx
- store/book.ts
- store/video.ts
- utils/book.ts
> fix: 提供中ブック視聴途中でブックが最初から再生される問題の修正

- server/utils/book/importBooksUtil.ts
- server/utils/topic/wowzaUpload.ts
- server/utils/wowza/upload.ts
- server/utils/zoom/api.ts
- server/utils/zoom/import.ts
timezone プロパティ自体ドキュメントに存在しないようなので廃止して、代わりにサーバーのデフォルトタイムゾーン (Intl.DateTimeFormat().resolvedOptions().timeZone) を利用するように変更
fixed npocccties/chibichilo#818
> fix: `Invalid time value`エラーの修正

- components/organisms/Video/VideoResource.tsx
- components/organisms/Video/index.tsx
- store/video.ts
ref #807 #808
- fix: 動画プレイヤーオブジェクトが重複する問題の修正
- fix: 動画プレイヤーオブジェクトプールに存在しない問題の修正
> fix: 動画プレビューの問題の修正

- components/organisms/BookForm.tsx
- package.json
- yarn.lock
ref #839
`@mui/lab/DateTimePicker` → `@mui/x-date-pickers` に移行されたのでその対応
> fix: ブックの公開にチェックを入れたとき「公開期限」の設定が表示されない問題の修正

- components/organisms/CourseTree.stories.tsx
- components/organisms/CourseTree.tsx
- components/templates/Courses.tsx
ref #785
~TODO:LMSが複数になると表示がおかしくなると思うので修正する。~
> 階層構造のLMS部分は表示しない

- server/utils/topic/topicToTopicSchema.ts
ref #779 
#824  であげられていた重複するブックを表示しない修正を行いました。
↑での実装をそのまま参考にさせて頂きました🙏ありがとうございます。
レビューよろしくお願いします！
> [トピック一覧] 重複するブックを表示しない

- components/organisms/CourseTree.stories.tsx
- components/organisms/CourseTree.tsx
- components/templates/Courses.stories.tsx
- openapi/models/InlineResponse2002Contents.ts
- server/models/link/content.ts
- server/models/link/search.ts
- server/prisma/migrations/20221025143108_add_lti_resource_link_update_at/migration.sql
- server/prisma/schema.prisma
- server/utils/linkSearch/linkSearch.ts
- utils/getLocaleDateStringUpToSecond.ts
- utils/getLocaleDateTimeString.ts
関連 #787 
LTIリンクの情報を増やす作業ですが、まずは作成日の追加を行いました。
正直あまりデザインに自信がないので、ご指摘よろしくお願い致します。
更新日の追加も行う予定ですが、作成日と横並びになるイメージをしてはいます。
> LTIリンクの情報を増やす

- package.json
- server/package.json
package.json の version フィールドを v2.3.0 に変更します。
> chore: bump minor version

- server/prisma/migrations/20230407112834_version_management/migration.sql
- server/prisma/schema.prisma
- server/utils/book/createBook.ts
- server/utils/book/importBooksUtil.ts
- server/utils/zoom/import.ts
ref https://github.com/npocccties/chibichilo/issues/884
https://github.com/npocccties/chibichilo/issues/872#issuecomment-1396481719 から、以下の点を変更しています。
- Book に Branch, Release 両方への参照を含めた
- Book から Release への参照が null のとき未リリースであるとした
- Release から、released フラグと createdAt を削除した
以下のコマンド操作で動作を確認しました。
```sh
$ cd server
$ npx prisma migrate dev
$ cd ..
$ yarn dev
```
間違えてプルリクをこちらに出してしまいました。
https://github.com/RCOSDP/GakuNinLMS-LTI-MC/pull/11
> feat: 版管理 リリース、ノードモデルの追加

- server/config/routes/book.ts
- server/models/book/release.ts
- server/services/book/release/index.ts
- server/services/book/release/update.ts
- server/utils/book/upsertRelease.ts
ref https://github.com/npocccties/chibichilo/issues/885
APIをswaggerから投入して、サーバでメッセージ出力するところまで実装しました。
引き続き DB にリリース情報を upsert する部分を作成します。
> feat: ブックをリリースするAPI追加

- components/atoms/Card.stories.tsx
- components/atoms/Card.tsx
- components/atoms/StripedMarkdown.stories.tsx
- components/atoms/StripedMarkdown.tsx
- components/molecules/SectionsTree.tsx
- components/organisms/ReleaseForm.stories.tsx
- components/organisms/ReleaseForm.tsx
- components/organisms/ReleasedBookCard.stories.tsx
- components/organisms/ReleasedBookCard.tsx
- components/organisms/SectionsTreeView.stories.tsx
- components/organisms/SectionsTreeView.tsx
- components/templates/ReleaseEdit.stories.tsx
- components/templates/ReleaseEdit.tsx
- components/templates/ReleasedBook.stories.tsx
- components/templates/ReleasedBook.tsx
- package.json
- samples/book.ts
- samples/index.ts
- samples/release.ts
- samples/sections.ts
- server/models/book/release.ts
- utils/getLocaleDateString.ts
- utils/getLocaleDateTimeString.ts
- yarn.lock
resolved #886
- ReleasedBook … リリース後のブック編集画面
- ReleaseEdit … リリース画面
デモ (Storybook)
ReleasedBook:
https://chibichilo-gh-886.vercel.app/storybook/index.html?path=/story/templates-releasedbook--default
ReleaseEdit:
https://chibichilo-gh-886.vercel.app/storybook/index.html?path=/story/templates-releaseedit--update
スクリーンショット
ReleasedBook:
ReleaseEdit:
> feat: リリース画面 (コンポーネント)

- openapi/apis/DefaultApi.ts
- server/config/routes/book.ts
- server/models/book/tree.ts
- server/services/book/tree/index.ts
- server/services/book/tree/show.ts
- server/utils/book/findTree.ts
ref #892
swagger から APIを呼び出して、ダミーデータが戻るところまで実装しました。
引き続き DB からデータを取り出して返信する部分を作成します。
> feat: ブックのツリー情報を取得するAPI追加

- openapi/apis/DefaultApi.ts
- server/config/routes/book.ts
- server/services/book/fork/create.ts
- server/services/book/fork/index.ts
- server/utils/book/forkBook.ts
- utils/book.ts
- utils/useBookEditHandlers.ts
resolved #888
- フォーク機能を提供します
- フォークするためのAPIを提供します
> feat: フォーク機能

- components/templates/BookTreeDiagram.tsx
バージョンツリー画面で作成者を表示します。
作成者以外の author は表示しません。
作成者が複数存在するときは、, 区切りで横に並べて表示します。
> show creator name

- components/organisms/BookTreeDialog.tsx
- pages/book/tree/index.tsx
ref #893 
バージョンツリー画面でノード(〇印の部分)をクリックすると、そのブックの詳細を表示します。
> バージョンツリー画面でブック詳細を表示

- components/organisms/AppBar.tsx
- components/organisms/ContentPreview.tsx
- components/templates/Books.tsx
> UI: Deep Linking でのリンクの選択画面でのいくつかの操作の廃止

- components/atoms/AuthorFilter.tsx
- components/atoms/SharedFilter.tsx
- components/templates/Books.tsx
- components/templates/DeepLInkBooks.stories.tsx
- components/templates/DeepLinkBooks.tsx
- pages/books/index.tsx
#971
Deep Linkの画面レイアウトを調整してみました。
アコーディオンのUIを採用してみましたが、もっと良さそうなUIあればコメント頂けますと🙏
https://github.com/npocccties/chibichilo/assets/47715432/6d4ddb08-25f4-4d08-a879-847a9b4b14a2
> fix:Deep Linking でのリンクの選択画面のレイアウトの改善

- server/services/ltiDeepLinking.ts
> feat: Deep Linking 利用時 LMS 側にある元のタイトルと説明文をそのまま使う

- pages/_app.tsx
- yarn.lock
> fix: ブック公開のページが表示されない

- pages/book/edit/index.tsx
- server/utils/uniqueId.ts
- utils/useReleaseBooks.ts
以下の点を修正しました。
- ブックをリリースしたとき、サーバ側で不要なデバッグメッセージが出力される
- ブック編集画面: リリースを[更新]したあと、リリース一覧が更新されない
> feat-vm2 ブランチの修正

- components/organisms/BookForm.tsx
- components/organisms/MetainfoForm.tsx
- components/organisms/ReleaseForm.tsx
- components/templates/BookEdit.tsx
- components/templates/BookEditReleased.tsx
- server/models/author.ts
以下の作業を行いました。
- 作成者から管理者を削除する
- 編集中に、ブック/トピックを削除するボタンを追加する
- ブック編集 公開機能とメタ情報の編集を調整
- リリースの更新ボタンの動作を修正
> UI関連の残作業の一部と修正

- components/organisms/AppBar.tsx
- components/organisms/MoveDownloadPageDialog.tsx
- server/utils/activity/findAllActivity.ts
- utils/useActivityByConsumer.ts
resolved: #1077 
ダウンロードページの全コース視聴分析データ（CSVファイル）は「他コースを含めた活動分析」相当のデータは含まないようにしました。
> feat: ダウンロードページでは他のコースを含めた活動を取得しない

- components/organisms/Video/index.tsx
- components/templates/Book.tsx
- utils/authorList.ts
著作権者が設定されていないときは、視聴画面で "作成者: 太郎先生" などのように表示します。
> fix: 作成者などを表示する

- components/organisms/Video/index.tsx
> fix: ビデオプレイヤーの固定表示機能を復旧
