.eslintrc.js
ルールの説明はこちら
https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/explicit-module-boundary-types.md
型アノテーションを律儀にやるのであれば有効でも良いのですが、既存のコーディングスタイルと記述量が増える点を考慮すると、offでよいかなあと思いました
=> chore: disable a rule of "@typescript-eslint/explicit-module-boundary-types"

.storybook/main.js, components/atoms/Button.stories.tsx, components/atoms/SearchTextField.stories.tsx, components/atoms/SearchTextField.tsx, components/atoms/SortSelect.stories.tsx, components/atoms/SortSelect.tsx, components/atoms/TextField.stories.tsx, components/atoms/TextField.tsx, components/atoms/Typography.stories.tsx, components/organisms/BookForm.stories.tsx, components/organisms/BookForm.tsx, components/organisms/Dialog.stories.tsx, components/organisms/TopicForm.stories.tsx, components/organisms/TopicForm.tsx, styles/card.ts, styles/input.ts, styles/inputLabel.ts, styles/select.ts, styles/textField.ts, tsconfig.eslint.json, tsconfig.json
=> コンポーネントの追加

.github/workflows/build.yml
actions/checkout@v2でrefのinputを設定することで、HEADの上でciを動かせるようですね
githubコンテキストの github.head_ref でHEADを指定できるようです https://docs.github.com/ja/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#github-%E3%82%B3%E3%83%B3%E3%83%86%E3%82%AD%E3%82%B9%E3%83%88
参考: https://qiita.com/Ouvill/items/7b6df0e9b981093b330f#pull-request-%E3%82%92%E3%82%82%E3%82%89%E3%81%A3%E3%81%9F%E3%81%A8%E3%81%8D%E3%81%AB-pr-%E3%83%96%E3%83%A9%E3%83%B3%E3%83%81%E3%82%92%E6%95%B4%E5%BD%A2
=> fix: format stepのときdetached HEADでcommitできない

.github/workflows/build.yml, package.json
サーバー側には jest を導入済み。yarn --cwd server test でいくつかテストケースが実証される。
クライアント側には未導入。﻿
yarn test するとひとまず chibichilo-server の yarn test だけが実行される
本PRではGitHub Actionsのなかで継続的に yarn test を実行するようにしました。
=> feat: add test action

.storybook/main.js
yarn storybookを実行した際に以下のエラーが出たので、それを解消するPRです
```
$ yarn storybook
yarn run v1.22.5
$ start-storybook
info @storybook/react v6.1.1
info 
info => Loading presets
info => Loading presets
info => Loading custom babel config as JS
info => Loading custom babel config
info => Loading custom babel config as JS
info => Loading custom babel config
info => Loading 1 config file in "./.storybook"
info => Adding stories defined in ".storybook/main.js"
info => Using cached manager
ERR! TypeError: path.basename is not a function
ERR!     at /var/home/kimiaki/Workspace/github.com/npocccties/ChibiCHiLO/.storybook/main.js:8:27
ERR!     at Array.map (<anonymous>)
```
=> fix: path.basename is not a function

server/models/book/section.ts, server/utils/book/destroyBook.ts, utils/book.ts, utils/ltiResourceLink.ts, utils/topic.ts
#96, #110 関連
クライアントのためのAPIの提供
- feat: useTopic hook
- feat: {create,update,destroy}Book
- feat: {create,update,destroy}Topic
- fix: 関連するltiResourceLinkが存在する時bookが削除されない問題を修正
=> ブックの作成/更新/削除/トピックの詳細の取得/更新/削除クライアントAPI

components/organisms/BookAccordion.stories.tsx, components/organisms/BookAccordion.tsx, components/organisms/BookPreview.stories.tsx, components/organisms/BookPreview.tsx, components/organisms/TopicViewer.stories.tsx, components/organisms/TopicViewer.tsx, components/templates/Book.tsx, components/templates/BookImport.tsx, components/templates/BookLink.tsx, components/templates/Books.tsx
https://github.com/npocccties/ChibiCHiLO/pull/119/files#r546573061 で書いたように、topicとbookを
スプレッド構文でわたすのではなく、そのままtopic propとbook propでわたすように変更しました
=> refactor: no use spread literal to topic book props

components/organisms/BookChildren.tsx, components/organisms/SubtitleUploadDialog.tsx, components/organisms/TopicForm.tsx, components/templates/Book.stories.tsx, components/templates/Book.tsx, components/templates/BookEdit.stories.tsx, components/templates/BookEdit.tsx, components/templates/TopicEdit.stories.tsx, components/templates/TopicEdit.tsx, components/templates/TopicNew.stories.tsx, components/templates/TopicNew.tsx, openapi/models/InlineResponse2001Sections.ts, pages/book.tsx, pages/book/edit.tsx, pages/book/new.tsx, pages/book/topic/edit.tsx, pages/book/topic/new.tsx, pages/books.tsx, pages/index.tsx, server/models/book/section.ts, server/models/videoTrack.ts, server/services/videoTrack/show.ts, server/utils/book/destroyBook.ts, server/utils/topic/destroyTopic.ts, server/utils/videoTrack/createVideoTrack.ts, store/book.ts, store/topic.ts, utils/topic.ts, utils/videoResource.ts, utils/videoTrack.ts
close #99, close #98 
- feat: support resource.url in TopicForm
- refactor: TopicPreviewDialogをBookEditに隠蔽
- feat: トピック作成機能 - fix: SubtitleUploadDialog submitイベントに反応させないように再構成 - feat: onTopicNewClickの注入 - refactor: TopicNew: 作成時デフォルトは空 - feat: create pages/book/topic/new
- refactor: query.bookIdと明示
- feat: create pages/book/topic/edit.tsx
- feat: onItemEditClick/onTopicEditClick注入
- fix: トピック削除できない問題への対処 リソースの削除の可否によらずトピックを取り除けるようにした
- fix: ブック削除してもトピックが残り続ける問題への対処 参照無ければ消す
- feat: トピック削除機能
- fix: query.prev が空なら含めない
- feat: トピック作成後ブラウザバックすると作成したトピックの編集画面
- feat: セクション追加機能
- fix: セクション名が得られない問題の修正 - chore: yarn build:openapi
- refactor 冗長な条件分岐の削除
- refactor: VideoTrackProps["content"]はBlobも許容しておく 大きいサイズだとメモリリークの恐れがあるため将来的にはBlobにしたい
- fix: CORSで保護されているのでセッションにアクセスしない/console.logを取り除く
- …
=> トピック作成・編集画面実装

components/molecules/BookChildrenTree.stories.tsx, components/organisms/BookAccordion.stories.tsx, components/organisms/BookAccordion.tsx, components/organisms/BookEditChildren.stories.tsx, components/organisms/BookEditChildren.tsx, components/templates/BookEdit.stories.tsx, components/templates/BookEdit.tsx, components/templates/Books.tsx, pages/book/edit/index.tsx, pages/book/edit/topic/edit.tsx, pages/book/edit/topic/index.tsx, pages/books/index.tsx, pages/books/topic/edit.tsx, pages/books/topic/index.tsx
マイブックとブック編集からそれぞれトピック編集に遷移して、編集後に元の画面に遷移するようにしました
=> マイブックとブック編集にトピック編集の動線を追加

pages/book/import/index.tsx, pages/book/topic/import/index.tsx, pages/link.tsx, utils/book.ts, utils/books.ts, utils/topic.ts, utils/topics.ts
close #190
リンク時のデフォルトの振る舞いを自身以外の作成したトピックへの影響を及ぼすのを避けるためにトピックの参照→トピックの複製に修正しました。
- refactor: $utils/topic,bookへ整理 - sharedOrCreatedBy - connectOrCreateBook - connectOrCreateTopic
- fix: 自身以外の作成した共有されていないトピックは含めない
- fix: 自身以外の作成者のトピックの複製
なおリンク OR 複製 等の選択は本PRでは対応しません。
=> ブック連携時のブックの複製をする際にブック内のトピックも複製

server/config/app.ts
Set-CookieのデフォルトがSameSite=Laxに変更され、SameSite=Lax では iframe に埋め込み時 Cookie が送信されないためSameSite=Noneを指定
確認したこと: SameSite=None が加わっていること。
$ diff -u <(curl -si https://chibi-ch-i-lo.ties-makimura.vercel.app/api/v2/session) <(curl -si https://chibi-ch-i-lo-git-fix-lanch-in-iframe.ties-makimura.vercel.app/api/v2/session)
```diff
--- /dev/fd/63	2021-02-05 19:41:30.622416392 +0900
+++ /dev/fd/62	2021-02-05 19:41:30.626416414 +0900
@@ -14,13 +14,13 @@
content-length: 2
x-frame-options: SAMEORIGIN
x-content-type-options: nosniff
-set-cookie: sessionId=DAbZzypueLT8hcXTp27sgVOBxg_-g1ZL.xlZ8AmAQm17CZrr1%2FMXiK%2FPGgDt9nOztAnW2lssW1rY; Path=/; HttpOnly; Secure
+set-cookie: sessionId=xvZkZ_ozxZN09igowMH7tB1QFgmHpE6Q.X1TvKsyJuaxMZHnDLUGedoSz56y%2BB2c4gWJhLN8zwfg; Path=/; HttpOnly; Secure; SameSite=None …
```
=> fix: ifame内で起動できない問題への対処

server/services/ltiResourceLink.ts, utils/ltiResourceLink.ts, utils/session.ts
updateLtiResourceLink実行後にsessionに反映されていない問題の修正。
一応useLtiResourceLink()を使うと回避できるが使われておらずsessionを中心にしているためsessionに反映。
=> fix: ltiResourceLink更新後sessionに反映されない

.eslintrc.yml, components/molecules/TopicViewerContent.tsx, components/organisms/BookNotFoundProblem.tsx, components/organisms/TopicNotFoundProblem.tsx, components/organisms/TopicViewer.tsx, package.json, store/playerTracker.ts, utils/activity.ts, utils/eventLogger/logger.ts, utils/eventLogger/playerTracker.ts, yarn.lock
つい気になったのでfilenames/match-exportedを追加
- `pages/**` default export を使うのは Next.js の仕様で明らか
なので無視
- `types/**`, `server/types/**` camelCase のまま保持
- いくつかリネーム﻿
=> refactor: export default とファイル名の一致を検証

server/main.ts, server/package.json, server/utils/staticHandler.ts, yarn.lock
fix #215
```sh
yarn build && API_BASE_PATH=/api/v2 FRONTEND_ORIGIN=http://localhost:8080 FRONTEND_PATH=/ SESSION_SECRET=super_secret_characters_for_session OAUTH_CONSUMER_KEY=test OAUTH_CONSUMER_SECRET=test DATABASE_URL=postgresql://postgres:password@localhost/postgres yarn --cwd server start
```
等で起動 => ブラウザーから起動後のエンドポイントにアクセスし.htmlの含まないURLの画面にアクセスする (/books, /book?bookId=1 等) => リロードして表示されることを確認
=> fix: 拡張子.htmlを含まないURLでのアクセスが404になる問題の修正 - fastify-static の代わりに serve-handler を使う

pages/topics/new.tsx, store/book.ts, store/videoTrack.ts
もともとPR #223 にて含めていたが #223 の内容とは直接関係ないのでcherry-pick
マウント以外の理由でリセットしなければならないユースケースの優先度は低いと考え useVideoTrackAtom 内に隠蔽、加えてアンマウント後のタイミングに変更してみましたが、問題あるかどうか確認ください bow > @knokmki612
=> fix: 以前のフォームの状態を保持し続けている問題の修正/コードの整理 - store/book.ts, store/videoTrack.ts: アンマウント後リセット

openapi/apis/DefaultApi.ts, pages/topics/edit.tsx, server/services/topic/destroy.ts, server/utils/topic/destroyTopic.ts
fix #229
確認したこと:
ブックにトピックをインポート、そのトピックを削除し、セクションの残骸が残らず、番号が1から振られていること
=> fix: セクションが空になるケースへの対処/ブックから参照されている場合、そのブックから取り除く

server/services/book/destroy.ts, utils/book.ts
LTIリソースとしてリンクされているブックを削除後、「LTIリンク」ボタンを押すと、「ブックがありません」エラー画面が表示される不具合があったのでその問題を解決
=> fix: ブック削除後のLTIリソースリンクとの不整合の修正

utils/books.ts, utils/topics.ts, utils/useInfiniteProps.ts, utils/userBooks.ts, utils/userTopics.ts
それぞれ一覧画面で読み込み中が意図せず発生するケースへの対処です
=> fix: ゼロ件のとき読み込み中になり続ける問題の解決

components/organisms/ActionHeader.tsx, components/organisms/AppBar.tsx, components/templates/BookImport.stories.tsx, components/templates/BookLink.stories.tsx, components/templates/Books.stories.tsx, components/templates/TopicImport.stories.tsx, components/templates/Topics.stories.tsx, pages/_app.tsx
#238 の改善です
以下のスクリーンショットのように、
100px程度スクロールした段階で
- 上部AppBarが非表示になる
- ActionHeaderはタイトルは張り付かず、ソートと検索のみ固定表示になる
ように変更しました
=> feat: use Slide with AppBar & ActionHeader

components/organisms/ActionHeader.tsx
https://github.com/npocccties/ChibiCHiLO/pull/243#issuecomment-785729721 :
> そうですね…ActionHeaderの固定表示部分はAppBarの下部に隙間なく張り付く想定で配置しているので、アニメーションの発火するタイミングの違いで微妙に隙間が生じますね。
> 対策としては、ActionHeader側でAppBarと重なる領域を用意しておけば、気になりにくいように改善できそうです。
16px分AppBarと重なる領域を用意しました
=> fix: 固定表示時にAppBarとActionHeaderの間に隙間が生じる

components/templates/BookEdit.tsx
デザイン検討段階で
- 「トピック・セクションの編集」「ブックの内容」という中見出しがあった
- タイトルにブック名を含めていた
のですが、実装段階で入れていなかったので追加しました
=> feat: ブック編集に中見出しを追加&タイトルにブック名を表示

components/organisms/Video/VideoJs.tsx, server/models/event.ts, utils/eventLogger/logger.ts, utils/eventLogger/playerTracker.ts
close #232 
確認したこと:
1. 開発用サーバーの起動
2. 学習者権限のアカウントでのYouTube動画の含まれるブックを起動
3. シークボタンを押す
4. サーバーのコンソールに"forward" "back" と共に押したタイミングでの再生時間 (秒) が含まれる文字列が出力
=> feat: forward, backイベントのサポート

server/utils/ltiv1p1/oauth.test.ts, server/utils/ltiv1p1/oauth.ts
- docs: use plural form param→params
- fix: [RFC 3986](https://tools.ietf.org/html/rfc3986)予約語が含まれる時の問題の修正
=> fix: RFC 3986予約語が含まれる時の問題の修正

server/services/book/update.ts, server/services/topic/update.ts, store/session.ts
fix #260
- fix: トピック・ブック更新時の作成者・著作者を変更しない
- fix: 管理者は他者の作成したトピック・ブックの編集画面にもアクセス
管理者権限は他者が作成したものも閲覧や編集、LTIリンクができることを確認。
=> fix: 他者の作成したトピック・ブックの編集画面への管理者のアクセス許可

.eslintignore, package.json, server/.gitignore
distディレクトリに配置されていないことによって `yarn build` 実施後、`node dist/index.js` 実行した際404になっていたため修正。
- fix: publicディレクトリがdistに配置されない問題の修正
- chore: eslintignore により具体的なパスを明示
=> fix: publicディレクトリがdistに配置されない問題の修正

components/organisms/BookEditChildren.tsx
再現手順
1. 任意のブックの編集画面にアクセス
2. ブック内セクション・トピックがあらかじめ存在することを確認
3. 「並び替え・セクションの編集」ボタンをクリック
結果
「新しいセクション」ボタンのみ表示され、存在していたセクション・トピックが表示されない
---
という現象の修正です
=> fix: 並び替えモードになった際にセクション・トピックが存在しない

components/organisms/BookForm.tsx, components/organisms/TopicForm.tsx
=> feat: 作成フォーム内の「他の編集者に共有」フィールドのデフォルトのcheckedを取り除く

components/molecules/BookTree.tsx, components/organisms/BookAccordion.tsx, components/organisms/BookPreview.tsx, components/organisms/TopicPreview.tsx
close #284
- マイブック
- マイトピック
- LTIリソースとのリンク
- ブックからインポート
- インポート
の箇所で、共有中のブック・トピックは専用のインジケータが表示されるようにしました (クリッカブルな部品との識別があまりよくないようにみえますが、その点は別途改善したいです)
=> feat: 共有中のブック・トピックを識別できるように

components/molecules/BookChildrenTree.tsx
=> feat: BookChildrenTreeで共有中のトピックを識別できるように

components/organisms/BookEditChildren.tsx, styles/card.ts, utils/useSortableSectionsProps.ts
closes #259 #264 #265 #266
- 「並び替え・セクションの編集」は「セクションの編集」という文言に
- ボタンではなくスイッチで切り替えるように
- モード切替時に永続化ではなく、保存ボタンで永続化に (#264 ではなく #265 で実装)
- 編集中にリセットできるように
- 編集未保存時は保存していないことをアラートするように
=> feat: 保存は保存ボタンで&リセットできるように&変更未保存はアラートする

components/atoms/SharedIndicator.stories.tsx, components/atoms/SharedIndicator.tsx, components/molecules/BookChildrenTree.tsx, components/molecules/BookTree.tsx, components/organisms/BookAccordion.tsx, components/organisms/BookPreview.tsx, components/organisms/TopicPreview.tsx
アイコンは、変更前だと自分以外のある集団に共有しているというより、全世界に公開しているようなイメージになっており、より適切なものがあるのではないかというフィードバックをいただいての変更です
=> feat: 共有インジケーターをコンポーネントに切り出し&アイコン差し替え

components/molecules/TopicViewerContent.tsx, components/organisms/BookForm.tsx, components/organisms/BookItemDialog.tsx, components/organisms/TopicForm.tsx, components/organisms/Video/HlsPlayer.tsx, components/organisms/Video/VideoJs.tsx, components/organisms/Video/Vimeo.tsx, components/organisms/Video/VimeoPlayer.tsx, components/organisms/Video/YouTubePlayer.tsx, components/organisms/Video/index.tsx, openapi/models/InlineResponse200.ts, openapi/models/InlineResponse2001Books.ts, server/models/book.ts, server/utils/book/aggregateTimeRequired.ts, server/utils/book/createBook.ts, server/utils/book/updateBook.ts
close: #33
- feat: トピックの学習時間の自動入力機能 - トピックの学習時間がまだ入力されていない、または無効値のとき、動画の情報をもとに自動入力されます - YouTube, Wowza については再生開始後取得
- fix: ブックの詳細のダイアログの表示項目の誤りを修正
- feat: ブックの学習時間の自動集計 - ブック作成・編集画面から学習時間フィールドを取り除く - Swagger フォーマットの修正 - yarn build:openapi
- fix: トピックの詳細の表示の誤りを修正
本PRにて各トピックの学習時間の合計を集計しブックの学習時間とする機能が加わりました。
それにともないブック作成・編集時の学習時間のフィールドは不要(少なくとも重要でない)と判断し取り除きました。(もし仮にブック作成・編集時の学習時間のフィールドを残すとして、その場合、自動集計の結果と手動入力の結果の不整合が発生しうる。その対処が必要となります。)
もし問題あるようであれば修正します。 > @horimasumi
=> feat: 学習時間の自動集計・自動補完

package.json
fix #218
Vercelでのビルドプロセスから余計な build:export を取り除きました。
https://chibi-ch-i-lo-git-fix-vercel-swagger-ui-ties-makimura.vercel.app/api/v2/swagger/static/index.html にアクセスできることを確認。
=> fix: VercelでSwagger UIにアクセスできない不具合の修正

store/session.ts, utils/session.ts
セッションを持たずアクセスしたときエラー画面が表示されるように修正しました。
=> fix: セッションのエラーが適切にハンドリングされず読み込み中になり続ける問題の修正

server/package.json
`yarn --cwd server migrate:reset` を実行する際にprisma/seed.tsが自動実行されるが失敗するので`--skip-seed` フラグでオプトアウト。
https://www.prisma.io/docs/reference/api-reference/command-reference#migrate-reset
=> fix: `yarn --cwd server migrate:reset` の不具合の修正

components/molecules/BookChildrenTree.tsx, components/organisms/BookChildren.tsx, components/organisms/BookPreview.tsx, components/organisms/TopicPreview.tsx, styles/lineClamp.ts, utils/outline.ts
close #151
- BookPreviewで使用する、章立てとタイトルの組み合わせでstringにする `getSectionsOutline` の実装
- "無名のセクション" などの章立てのロジックを `isNamedSection` に切り出し
- --webkit-line-clampとそのフォールバックのスタイルを生成する `$styles/lineClamp` の実装
- BookPreviewとTopicPreviewのスタイルの調整
=> feat: トピック・セクションの省略表示

components/molecules/TopicViewerContent.tsx, components/organisms/TopicPreviewDialog.tsx, components/templates/Book.tsx
- BookPreviewのmediaQuery周りのスタイルを `&$modifier` に移動
- TopicViewerContentのstickyをpropsで分離
- ブック閲覧の見出しをモバイル表示時フォントを小さく&折り返さず省略
>  TopicViewerContentのstickyをpropsで分離
TopicViewerにもposition: stickyが効いていたのですが、実際にはブック閲覧ページにてstickyのスクロール追従が機能していなかった(TopicViewerに対して `overflow: visible` の設定が必要)でした。機能していないスタイルが当たっている状態は改善すべき立ったので取り除かれるようにしました
=> feat: ブック閲覧周りのスタイル調整

components/organisms/BookForm.tsx, components/organisms/TopicForm.tsx
シェアインジケーター #289、アプリケーションバーでは、「編集者」ではなく「教員」という名称を用いているので、それに揃える変更になります
=> feat: 文言変更: 編集者→教員

components/organisms/Video/HlsPlayer.tsx, components/organisms/Video/VideoJs.tsx, components/organisms/Video/Vimeo.tsx, components/organisms/Video/VimeoPlayer.tsx, components/organisms/Video/YouTubePlayer.tsx, components/organisms/Video/index.tsx, components/templates/Book.stories.tsx, components/templates/BookLink.tsx, pages/book/index.tsx, store/book.ts, utils/eventLogger/logger.ts, utils/eventLogger/playerTracker.ts
fix #21 
- pages/book/index.tsx: 次のトピックの再生に進む処理とnextvideoイベント発火の共通化
- Videoコンポーネント: propsでイベントハンドラーを渡さずPlayerTrackerを介して依存性 (onEnded, onDurationChange) 注入することで繰り返し描画され続ける問題を回避
確認したこと:
`yarn build && yarn start | grep changepage` して開発サーバーを起動後、学習者としてシステムにアクセス、手動・自動問わず切り替えたタイミングで適切にコンテンツ(トピックのID)が得られることを確認 (YouTube, Vimeo, Wowza)。
=> fix: 自動切り換えの時 changepage イベントログが得られない不具合の修正

components/molecules/TopicViewerContent.tsx, components/organisms/ActionHeader.tsx, components/organisms/TopicPreviewDialog.tsx, components/organisms/TopicViewer.tsx, components/templates/Book.tsx, components/templates/BookLink.tsx, styles/sticky.ts, utils/useStickyProps.ts
#299 に関連しています
アプリケーションバー、タイトルバーにスタックして、BookChildrenとTopicPlayerがStickyにスクロール追従します
=> feat: トピック・セクション一覧と動画プレーヤーのスクロール追従

components/organisms/BookPreview.tsx, components/templates/BookLink.tsx
それぞれ
- 「提供解除」ボタン: #316 
- 「もっと詳しく...」ボタン: #148
に対応しています
=> fix: 機能しないボタンをdisabled/非表示に

components/templates/Book.tsx
close #315 
ローカル環境にて、
1. 教員1が他の教員にシェアしないブックを任意のLTIリンクに提供
2. それぞれのアカウントから 1\. のLTIリンクにアクセス
という手順で
管理者: 鉛筆ボタンが表示される
教員1: 鉛筆ボタンが表示される
教員2: 鉛筆ボタンが表示されない
という結果になることを確認しました
=> fix: シェアされていないブックを閲覧している際にフォークが可能

components/atoms/CreatorFilter.tsx
#297 の議論を踏まえて、4択ではなく3択("none"の除外)を考慮したUIの変更です
https://chibi-ch-i-lo-git-feat-creator-filter-as-radio-group-ti-ab965b.vercel.app/storybook/index.html?path=/story/atoms-creatorfilter--default
=> feat: CreatorFilterは3択のRadioに

components/atoms/AppBarNavButton.stories.tsx, components/atoms/SubtitleChip.tsx, components/organisms/BookChildren.tsx, next.config.js
- fix: material-ui/icons のインポートプロセスの最適化
- fix: Next.js ビルド時の型検査をスキップ - ESLint によってカバーされているため不要と判断
2m5.0s → 1m13.8s (59.0%) に短縮。
計測方法: `time yarn build` in ThinkPad T490 i7 RAM 24GB, Ubuntu 20.04 LTS Desktop
最適化前:
```
#1
real    2m14.721s
user    6m20.656s
sys     0m21.324s
#2
real    1m55.409s
user    5m36.553s
sys     0m18.847s
```
最適化後:
```
#1
real    1m14.402s
user    3m16.786s
sys     0m10.940s
#2
real    1m13.134s
user    2m50.101s
sys     0m10.713s
```
<details>
<summary>
Storybook ビルド時間の改善: 1m34.8s→55.4s (58.4%)
</summary>
なお、Tree Shakingされているのでビルド後のサイズとパフォーマンスには影響ない様子(たぶん)。
計測方法: `time yarn build:storybook` 同環境
最適化前:
```
#1
real    1m39.491s
user    2m12.064s
sys     0m7.589s
#2
real    1m30.019s
user    1m50.925s
sys     0m6.831s
file size:
main (3.68 MiB) …
```
=> fix: ビルド時間の改善

.storybook/preview.tsx, components/templates/Book.stories.tsx, components/templates/BookEdit.stories.tsx, components/templates/BookImport.stories.tsx, components/templates/BookLink.stories.tsx, components/templates/BookNew.stories.tsx, components/templates/Books.stories.tsx, components/templates/Placeholder.stories.tsx, components/templates/TopicEdit.stories.tsx, components/templates/TopicImport.stories.tsx, components/templates/TopicNew.stories.tsx, components/templates/Topics.stories.tsx
templates以下のコンポーネントのストーリーブックを見ていると画面端の余白が気になったのでそれを取り除きます。
=> chore: templates stories, use fullscreen layout

components/organisms/TopicPreview.tsx
see also #314
次のページでのトピックの更新日と作成者の表示のサポート
- トピックの一覧
- トピックの再利用
=> feat: トピックの更新日の表示

components/molecules/TopicViewerContent.tsx, components/organisms/Video/Vimeo.tsx
close #354 , close #352 
- feat: 動画プレイヤーの背景色
- feat: 動画は最大40vhで解説領域を確保
- fix: Vimeoで動画表示前に高さが確保されない 
確認したこと
- 十分な文章量の解説を含んだトピックを作成し、ブック閲覧にてブラウザの縦幅を短くする
- 40vhの高さで動画領域が縮小されることを確認
- Vimeoの動画を登録したトピックを作成し、ブック閲覧にて当該トピックを表示する
- 16:9相当の領域がグレーの背景色とともに確保されていることを確認
=> feat: 閲覧時の動画は40vhを最大高さに&Vimeoの表示領域を確保するように

components/molecules/TopicViewerContent.tsx
以下のフィードバックの反映
「半分よりちょっと大きい」というリクエストに対して、3:4の動画の場合でちょうど半分になる程度に変更をしています。
プレビュー用のStorybookで確認いただくなどして、引き続き調整が必要であれば、このPRにて変更したいと思います
> 私の，1920×1080の画面では、動画がかなり小さいので，ここは決めの問題だとおもうので，シェアが高いとされている，1920×1080の画面で，半分よりちょっと大きい位の高さにできますでしょうか．
https://gs.statcounter.com/screen-resolution-stats/desktop-tablet-console/japan/#monthly-202003-202103
> 
> <img width="1441" alt="image" src="https://user-images.githubusercontent.com/9005132/113128770-1c52dc80-9255-11eb-8d89-1d5c9397dcc8.png">
_Originally posted by @horimasumi in https://github.com/npocccties/ChibiCHiLO/pull/359#issuecomment-810950088_
before(1920x1080の画面)
after(1920x1080の画面)
=> feat: TopicViewerContentの動画の最大高さ調整

.storybook/preview.tsx, components/organisms/Video/VideoJs.tsx, components/organisms/Video/YouTubePlayer.tsx, pages/_app.tsx, styles/video-js.css, utils/inIframe.ts
fix #373
- fix: iframe 内で再生ボタンが機能しない問題への対処
- fix: video-js.cssのCSS-in-JSへの移行
=> fix: iframe 内で再生ボタンが機能しない問題への対処

components/organisms/Video.stories.tsx, utils/buildTracks.ts
- fix: Video.stories.tsxへのWowzaのデモ動画追加
- fix: 開発環境でクロスオリジンのときblob schemeの字幕が反映されない問題の解決
ローカルの環境で `yarn storybook` 等開発サーバーを起動したとき `blob:` から始まるURLの字幕が表示されていない問題があったので修正
=> fix: 開発環境でクロスオリジンのときblob schemeの字幕が反映されない問題の解決

server/services/ltiLaunch.ts
並び順を提供しているリンクの名前順に変更したが提供しなければ変更後のリンクの名前が反映されないのは手間だと思うので誰かアクセスしてきたらその都度更新する
=> feat: LTIツールとして起動する度にタイトルとラベルを更新

components/molecules/TopicViewerContent.tsx
#437 に関連していますが、環境がないので検証できていないです
=> feat: 折り返しをflex-wrapではなくinline要素でおこなう

components/templates/Books.tsx
https://github.com/npocccties/chibichilo/issues/418#issuecomment-865507082 を改善します
変更前
変更後
「提供中のブック」の表示領域がウィンドウの表示領域内にある状態で異なるブックを提供すると、「提供中のブック」が存在しない場合に表示されるメッセージが瞬間的に表示される場合があります。その際のメッセージとBookPreviewの画面要素のheightが異なり、そのheight差分のぶん「ガクッと」一覧されるブックの表示位置が変動します。
この変更によって、「提供中のブック」がない場合に表示されるメッセージをBookPreviewの高さ相当に調節し、「ガクッと」表示位置が変動されることを抑制します。
また、この変更の副次的な要素としてBookPreviewに動画プレイヤーがない場合等の高さが微妙に異なる場合もあらかじめ所定の高さをminHeightによって指定しているため、こちらのケースについても表示位置の変動が抑制されます。
=> fix: 提供中のブックの有無で領域の高さが異なり表示位置がずれる場合がある

styles/input.ts
MuiTextFieldのスタイルのカスタマイズが不十分で、複数行入力の際の下辺の余白がなくつまっている状態でした。それを解消する変更です。
```
div.MuiInputBase-root
inputあるいはtextarea
```
というマークアップ構造で、単一行(input)時はinputに対してborderとpaddingを設定するので問題なかったのですが、複数行(textarea)時は、アウターdivに対してborderとpaddingの設定をしないと意図した余白になりませんでした。
変更前
変更後
=> fix: TextField multilineの下辺の余白がない

components/organisms/BookForm.stories.tsx, components/organisms/BookForm.tsx, components/templates/BookEdit.stories.tsx, components/templates/BookEdit.tsx, pages/book/edit/index.tsx
下記の対応です
> > 「他の教員にシェア」のチェックボックスの見せ方と，揃っていない
> 
> 意図はありまして、
> 
> - フォームの実線で区切ったものより上：ブックに持たせる情報の入力
> - 区切ったものより下：ブックに対する操作に関する情報の入力
> 
> なので何らかの方法で区別する必要があると考えていました
> 
> ただ「他の教員にシェア」と「更新したブックを提供」はフォーム内の他のラベルと異なり動名詞でのラベリングになっている点でも似ており、わざわざラベルのレイアウトで差別化するのは果たして適切なのかと自分でも思います
> 
> > すでに提供中なので，チェックできなくして提供中の文言に変えるなど，混乱しない配慮
> 
> 非活性にするのであればラベルの文言は変更せずに、注釈を別途表示するのがよいかと思いました。
> 
> 非表示にすることも考えられますが「提供中のブックに対して編集している」ことが分かる工夫がいずれにせよ必要になると思いました
> 
> _Originally posted by @knokmki612 in https://github.com/npocccties/chibichilo/issues/428#issuecomment-873759750_
> 非表示にすることも考えられますが「提供中のブックに対して編集している」ことが分かる工夫がいずれにせよ必要になると思いました
は検討してみたのですが、
- ブック編集に至るまでの動線で「提供中のブック(ブック視聴)」もしくは「ブック一覧」にて提供中のブックかどうか識別してアクセスするのでまったく提供中かどうかの情報提示がされないわけではない
- ブック編集上にブックの閲覧系の情報を配置したり動線を増やすのは #291 で検討したほうがいいのでは …
=> feat: 提供中は提供に関するオプションを表示しない&シェアと見た目を統一

components/atoms/BookChildrenItem.tsx
#459 時点で children propsが用意されておらず編集ボタンが表示されなくなっていました
=> fix: ブック視聴時にトピックの編集ボタンが表示されない

components/atoms/BookChildrenItem.tsx
https://github.com/npocccties/chibichilo/issues/410#issuecomment-878907091 への対応です
ツリー風の表示だが実際にはそれをアイコンで表現しているため、線が途切れ途切れになり違和感が生じていました。
- トピック、セクション名は折り返しせずはみ出た分は省略する
- 副作用としてTypographyのスタイルを省いたためフォントサイズが少し小さくなっている
- ListItemの表示間隔を狭める
- 後続のあるセクションは途切れ線で線がとぎれていることを提示する
という対処をしました
PRと直接関係ない変更を1点おこないました
- svg viewBoxが現状だと端の丸み処理がみきれていたので少し広げた
変更前
変更後
=> feat: ツリー表示をアイコンで表現している違和感を抑制するデザイン変更

docker-compose.yml, server/docker-compose.yml
fix #473 変更は開発者向けで本番環境ならびに本番相当環境への影響は無いと判断するためマージ後クローズしますね > @ties-makimura, @horimasumi 
やったこと:
- fix: bitnami/moodle デバッグ用環境変数の宣言
- fix: バージョンの不整合によって開発用のDocker Composeサービスの構築での失敗への対応
=> fix: 開発用のDocker Composeサービスの構築に失敗する問題の対応

components/organisms/BookChildren.tsx
#477 への対応です
`ListItem` に `ListItemSecondaryAction` が含まれているとcontainerが追加されマークアップ構造が変化し、CSSセレクタにマッチしないのが原因でした。子セレクタの代わりに子孫セレクタをつかうことで対処しています
=> fix: プレビュー画面と視聴画面でインデントが異なる

components/organisms/BookForm.tsx, components/organisms/BooksImportForm.tsx, components/organisms/SubtitleUploadDialog.tsx, components/organisms/TopicForm.tsx, package.json, yarn.lock
React Hook Form v7 へのバージョンアップしました。
Checkboxに関しては対応していないためsetValueを使うことで回避しました。
フォームを操作して問題なさそうなことを確認しました。
参考文献:
- [react\-hook\-form/CHANGELOG\.md at v7\.12\.0 · react\-hook\-form/react\-hook\-form](https://github.com/react-hook-form/react-hook-form/blob/v7.12.2/CHANGELOG.md)
- [Migrate From V6 to V7 \| React Hook Form \- Simple React forms validation](https://react-hook-form.com/migrate-v6-to-v7)
=> chore: migrate react-hook-form v6 → v7

components/organisms/TopicForm.tsx
動画から再生時間を取得するように利用者に促す目的
関連: #461
確認したこと:
備考: 差分を明らかにする目的で #494 のブランチをベースにしていますがマージ先は master ブランチの想定です。#494 マージ後 rebase などしてベースを変更するつもりです。
=> feat: 学習所要時間の項目の必須化

components/organisms/Problem.tsx
Warning: validateDOMNesting(...): <p> cannot appear as a descendant of <p>.
とブラウザーのコンソールに表示されていた
=> fix: 無効なHTML構造

components/organisms/TopicViewerContent.tsx
#504 への対応です
動画プレイヤーにmargin-bottomを持たせている分が画面上に反映されたりされなかったりしていたので、非表示時はmarginを持たせないようにしました
=> fix: ビデオエリアの上部が下にずれる

utils/video/getVideoJsPlayer.ts
`VIDEOJS: WARN: A plugin named "streamrootHls" already exists. You may want to avoid re-registering plugins!`
というメッセージがコンソールで表示される点への対処 https://github.com/npocccties/chibichilo/pull/499#issuecomment-903382446
=> fix: videojs-hlsjs-pluginが重複して登録される

utils/video/getVideoHolder.ts, utils/video/getVideoJsPlayer.ts, utils/video/getVimeoPlayer.ts
`VIDEOJS: WARN: The element supplied is not included in the DOM` への対処です
#497 への対応でもあります
=> fix: video.jsのiframeを要するソースでiframeが生成されない場合がある

utils/useVolume.ts
ready の変化のタイミングで余計な player.volume() を呼ばないようにプロセスを変更
関連: https://github.com/npocccties/chibichilo/issues/514
=> fix: ページ表示後すぐに音量を変更すると音量が変更前に戻る問題の修正

openapi/runtime.ts, openapitools.json, package.json, types/globalFetch.d.ts
TypeScript 3.6.2 で削除された GlobalFetch が openapi-generator によってデフォルトで生成されていたため、型宣言ファイルで上書きしていましたが、typescriptThreePlus オプションを使うことで対応可能なので削除しました。
https://openapi-generator.tech/docs/generators/typescript-fetch/#:~:text=false-,typescriptThreePlus,-Setting%20this%20property
﻿
=> fix: TypeScript 3.6.2 で削除された GlobalFetch の削除

next.config.js
参考文献:
- https://nextjs.org/docs/api-reference/next.config.js/ignoring-typescript-errors
- https://nextjs.org/docs/api-reference/next.config.js/ignoring-eslint﻿
=> fix: 現在使用されていないignoreDevErrorsオプションの削除/ignoreDuringBuilds オプション有効化

pages/book/new.tsx
ブック作成時にトピックを追加する旨の空の通知が意図せず表示される問題への修正です。
関連: https://github.com/npocccties/chibichilo/pull/534
=> fix: ブック作成時に「以下のトピックを追加します」と意図しない通知が表示される問題の修正

components/atoms/IconButton.tsx
`$atoms/IconButton` が非活性であるとき、以下のようなメッセージがコンソールに表示されます
```
MUI: You are providing a disabled `button` child to the Tooltip component.
A disabled element does not fire events.
Tooltip needs to listen to the child element's events to display the title.
```
公式ドキュメントにも[この点に関するドキュメンテーション](https://mui.com/components/tooltips/#disabled-elements)がされており、対処方法としては非活性な要素に対して異なる要素でラップする方法が案内されています
ちびチロにおいては、非活性時のツールチップ特有の文言を設定することは想定しておらず、非活性時ツールチップが表示されないことは却って都合のいい挙動だったので、その挙動を維持したまま警告が表示されないような変更が望ましいと考えました。
=> fix(IconButton): 非活性であるときにツールチップに関する警告が発生する

openapi/models/InlineObject6.ts, openapi/models/InlineObject7.ts, openapi/models/InlineResponse2001Contents.ts, openapi/models/InlineResponse2001Topics.ts, server/models/topic.ts
resolved #552
確認したこと:
開発用サーバー起動後 http://localhost:8080/api/v2/swagger/static/index.html#/default/put_api_v2_topic__topic_id_ にてライセンスフィールドを更新可能なこと
=> feat: トピックAPIのライセンス対応

server/config/routes/lti.ts, server/services/ltiLogin.ts
LTI v1.3 ログインエンドポイントにおいてHTTP GETリクエストのクエリ文字列﻿の参照に失敗していたため修正
=> fix: LTI v1.3 ログインエンドポイントにおいてHTTP GETリクエストのクエリ文字列﻿の参照に失敗していたため修正

components/organisms/TopicForm.tsx
関連: #551 
以下のようなライセンスのセレクターを追加しました
確認したこと
- 開発環境でトピック作成/編集によるライセンスの設定/設定解除ができること
差分を見やすくするためベースブランチを #593 にしています
=> feat: トピック作成/編集のライセンス対応

components/atoms/License.stories.tsx, components/atoms/License.tsx, components/organisms/TopicForm.tsx, components/organisms/TopicViewerContent.tsx, utils/licenses.ts
関連: #558 
- CC-BY-*-4.0 について https://creativecommons.org/choose/ で生成される埋め込みコードに近い見え方
- それ以外は[SPDY Licenses List](https://spdx.org/licenses/)のリンク
で表示されるようにしました
=> feat: ライセンスの表示

components/organisms/TopicForm.tsx
=> fix: トピック作成時ライセンス項目値が表示されるように修正

server/package.json, server/utils/search/bookSearch.ts, server/utils/search/parser.test.ts, server/utils/search/parser.ts, server/utils/search/query.ts, server/utils/search/topicSearch.ts, utils/search/stringify.ts, yarn.lock
resolved #550
使い方: (シェアされているものでの絞り込みの場合) 検索欄に `shared:true` と入力して検索
シェアされていないものは`shared:false`と入力して検索
=> feat: 共有可否フィルターのサポート

server/config/app.ts, server/config/validations.ts, server/models/topic.ts, server/package.json, server/prisma/schema.prisma, server/validators/license.test.ts, server/validators/license.ts, yarn.lock
resolved #589
- JSON Schema custom formats `"license"` を追加
=> fix: SPDX Licenseに適合するもののみ受け付けるライセンスのバリデーションの対応

components/atoms/AuthorFilter.tsx, components/atoms/ContentTypeIndicator.stories.tsx, components/atoms/ContentTypeIndicator.tsx, components/atoms/SearchTextField.tsx, components/atoms/Select.tsx, components/templates/Books.tsx, components/templates/Topics.tsx, styles/outlinedInput.ts
#555 への対応です
スクロール時追従する領域で、コンテンツの種類が分かるようにしました
ブック
トピック
=> feat: 一覧画面でのコンテンツの種類の表示, etc.

components/atoms/ContentTypeIndicator.tsx
#555 への対応です
コンテンツの種類の表示部分の文字を太字にし、大きさを1.25倍にすることで強調しました
=> feat: コンテンツの種類の表示を強調する

components/templates/Books.tsx, components/templates/Topics.tsx
以下への対応です
> > 「コンテンツの種類・ブック」という文字列を，並び順のソートの前にもってくるのは難しいのでしょうか？
> 
> 画面上の左上から目につきやすいという特性を考えれば、おっしゃるように一番左に配置するのは一定の理があるとおもいます。
> 
> なやましかった背景として、並べ替えという操作も一番左に配置されることが多く、そのような「見慣れたレイアウト」であることを優先するのか、このアプリケーション特有のコンテキストを優先するのか、という判断をおこなう必要がありました。
> 
> 結果的に私は「見慣れたレイアウト」であることを #607 の時点では優先したわけですが、今からその並びをかえることは理解できる判断であると思いました。
> 
> _Originally posted by @knokmki612 in https://github.com/npocccties/chibichilo/issues/555#issuecomment-986609709_
=> feat: コンテンツの種類は重要な情報なので一番左に配置する

components/atoms/SearchClearButton.tsx, components/atoms/SearchTextField.tsx, components/organisms/AuthorsInput.tsx, components/organisms/KeywordsInput.tsx, components/templates/BookImport.tsx, components/templates/Books.tsx, components/templates/TopicImport.tsx, components/templates/Topics.tsx, store/search.ts
#560 への対応です
- refactor: InputAdornmentが使用可能な場所への導入
- feat(SearchTextField): 検索ボタンの追加
- 検索実行のハンドラーの追加
- 再描画を抑制するdebouce、useStateの導入
- styled形式へのスタイルの移行
- 入力欄の文字列の状態管理の追加
=> feat: 検索欄での検索実行のタイミングを入力時から手動にする

store/search.ts
関連: #560
以下のような問題、変更内容への対応
> 
> > SearchTextField 外で query.q が更新される場合に、それを反映する
> 
> お粗末ながら現時点でもこの点について実現できておらず、次のような変更が必要ですね
> 
> ```diff
> diff --git a/store/search.ts b/store/search.ts
> index 745bdbb..ccfdca9 100644
> --- a/store/search.ts
> +++ b/store/search.ts
> @@ -71,19 +71,19 @@ export function useSearchAtom() {
>      (link) =>
>        updateQuery((query) => ({
>          ...query,
> -        q: clsx(query.q, stringify({ link: [link] })),
> +        q: clsx(input, stringify({ link: [link] })),
>          page: 0,
>        })),
> -    [updateQuery]
> +    [updateQuery, input]
>    );
>    const onKeywordClick: (keyword: KeywordSchema) => void = useCallback(
>      (keyword) =>
>        updateQuery((query) => ({
>          ...query,
> -        q: clsx(query.q, stringify({ …
```
=> fix: 検索欄の入力途中にキーワードをクリックすると検索欄の入力内容が失われる

components/atoms/SearchTextField.tsx
関連: #560
検索欄での入力後入力内容の `store/search` への反映が必要なケースは以下の2つ
1. onSearchSubmit発火時:
onSearchSubmitの発火時に入力内容が渡される
2. onKeywordClick/onLtiContextClick発火時:
debouncedなonSearchInputが事前に発火している
このうち2\.について、onKeywordClickないしonLtiContextClickが発火する際は
必ず検索欄からのフォーカスが外れている(onBlurが発火する)との仮定により
onSearchInputの発火タイミングをonChangeからonBlurに変更
debounceは頻繁なイベントの発火を抑制するために使用していたがonBlurでは不要
=> refactor: 不要なdebounceの除去

components/atoms/Markdown.tsx, components/organisms/BookInfo.tsx, components/organisms/TopicViewerContent.tsx
解説が空の場合にもネガティブマージンが適用されており
必要以上に縦幅が縮められている
変更前
変更後
=> fix: 意図しないネガティブマージンの適用

components/organisms/Video/index.tsx
関連: #553
確認したこと:
手元の開発用サーバーにて報告のあった手順で問題が再現しないことを確認
=> fix: 特定のケースでトピックプレビューが表示されない問題の修正 事前読み込みされる動画の除去プロセスの修正

utils/useContents.ts
検索のための操作後リクエストを間引くために遅延させていましたが、更新頻度の高い入力操作は input として分離され、リクエストを間引く重要性が低くなったため、その遅延処理を取り除きました。
=> perf: 検索時のリクエストの遅延の解消

.github/workflows/build.yml, package.json
関連: #539 
> > `/.eslintcache` を消すとエラーが表示されました。やはり(私の環境では)キャッシュ周りでリントをすり抜けたりあやまったエラーの検知がなされたりしている気がします
> 
> パフォーマンスとのトレードオフなのでそのあたりの問題は仕方ないという気もしますが、ESlintのキャッシュの構造としてもおそらくタイムスタンプとサイズのメタデータを管理しているだけの単純なものなので確かに脆弱すぎるかもしれないですね。yarnとyarn.lockに比べればeslintのパフォーマンスの影響は比較的小さいので--cache をデフォルトに含めずとも私はよいと思います。
CI上は適切にLint結果を返せているように思うので、ひとまずはアドホックに自分の環境で怪しく感じたらキャッシュを消すことでお茶を濁そうかなと思いました
_Originally posted by @knokmki612 in https://github.com/npocccties/chibichilo-qleap/issues/91#issuecomment-970084628_
`--cache-strategy (metadata|content)` のいずれにしても
依存しているファイルに変更があるが自身に変更がないファイルは
リントされてほしいにもかかわらずがスキップされるという問題があるため
=> chore(eslint): --cacheオプションの無効化

server/utils/search/parser.test.ts, server/utils/search/parser.ts, store/search.ts
関連: https://github.com/npocccties/chibichilo/issues/628
> ﻿「ライセンス：未設定」の場合，設定済みのトピックも表示されてしまいます．
この問題の修正です。
原因: `license:` の場合 search-query-parser のパース結果のオブジェクトのプロパティが追加されず、誤ってライセンスの指定のためのクエリー文字列が含まれないものとして解釈されていた
対処: `license:` は無効値なので使わず、代わりに `license:none` を使う
=> fix: 「ライセンス:未設定」が機能しない問題の修正

store/search.ts
#605 への対応
同じコースのLTIリソースリンクについては重複とみなさない処理になっていたため
=> fix: コースによる絞り込みが重複しうる

components/organisms/ContentPreview.tsx
関連 #627
表示例
疑問
ライセンスをクリックするとライセンスの要約文のページが開かれるが、クリックしたらクリックしたライセンスで絞り込まれる挙動に変更すべきかどうか
=> feat(ContentPrevie): ライセンスの表示

components/organisms/Search.tsx
関連: #602
折りたたまれている情報を展開するためのボタンを認識するコスト
折りたたまれている機能にアクセスするための効率性
という観点から取り除くことによる改善が期待される
=> feat:(Search): 折りたたみは不要

components/atoms/License.tsx
=> fix: コンソールにMUI: the styled("img")(...args) API requires...が表示される

components/atoms/CourseChip.tsx, components/atoms/KeywordChip.stories.tsx, components/atoms/KeywordChip.tsx, components/organisms/ContentPreview.tsx, components/organisms/FilterColumn.tsx, components/organisms/KeywordsInput.tsx
関連: #629
- refactor: KeywordChipとして外部化
- refactor(CourseChip): styledへの移行
- fix: コース名やキーワードが長いとはみ出る箇所がある
before
after
=> fix: コース名やキーワードが長いとはみ出る箇所がある, etc.

components/organisms/ContentPreview.tsx
=> feat: 文言統一「リンク」→「コース」

components/organisms/ContentPreview.tsx
現状だと提供中のコースが表示領域に収まらなければ省略されアクセス不可能となる。
省略せず折り返して表示することですべての提供されているコースに対してアクセス可能にする変更
変更前
変更後
=> feat: コンテンツごとの提供中のコースが省略されず表示されるように

components/atoms/CourseChip.tsx, components/atoms/KeywordChip.tsx
たくさんのツールチップが含まれた表示系が並んでいると、
ツールチップに被った表示系への操作が阻害される。
操作を阻害させないための変更
一部WCAG AA基準をパスしないことになる点に留意
See: https://mui.com/components/tooltips/#interactive
See: https://www.w3.org/TR/WCAG21/#content-on-hover-or-focus
=> feat: 一部のツールチップを非対話的な挙動にする

components/organisms/BookForm.tsx, components/organisms/TopicForm.tsx
関連: https://github.com/npocccties/chibichilo/issues/641
トピック・ブックのそれぞれ解説の入力欄のラベル中のリンクがクリックしても反応しないので、その構造と見た目の変更を行いました。
=> fix: GitHub Markdown へのリファレンスのリンクが機能していない問題の修正

components/organisms/Video/VideoPlayer.tsx, utils/eventLogger/logger.ts, utils/playbackRate.ts
ref #672
利用者によって手動で変更された場合と区別する目的で、再生速度がデフォルト値またはlocalStorageに記録されているものと一致しない場合は ratechange イベントが発報されないように変更しました。
この変更の副作用として、従来動画読み込み直後に発報されていた ratechange イベントについても発報されなくなりますので、確認してもらえればと思います。
=> feat: 動画プレイヤーの再生速度の設定を引き継がせる

server/utils/book/destroyBook.ts, server/utils/topic/destroyTopic.ts
#767 #768 の対応．
この対応では，何にも紐付かないキーワードがDB内に残り続けることになるが，どうあるべきかは別途考える．
=> fix: ブックやトピック削除時にキーワード削除は行わない

.github/workflows/build.yml
pull_request イベントで実行されるワークフローのときgit pushのタイミングでdetached HEADエラーになる。それを防ぐためのパッチです。
(7951be1b00c10bd4ae2a8562ffd88a5b71410b95 でエンバグ)
次のようなエラーが出ていた:
```
Run if git -c "user.name=bot" -c "user.email=bot@example" commit -am "bot: format"; then
[detached HEAD 539264a] bot: format
2 files changed, 6 insertions(+), 2 deletions(-)
error: The destination you provided is not a full refname (i.e.,
starting with "refs/"). We tried to guess what you meant by:
- Looking for a ref that matches 'HEAD' on the remote side.
- Checking if the <src> being pushed ('HEAD')
is a ref in "refs/{heads,tags}/". If so we add a corresponding
refs/{heads,tags}/ prefix on the remote side.
Neither worked, so we gave up. You must fully qualify the ref.
hint: The <src> part of the refspec is a commit object.
hint: Did you …
```
=> fix: 自動コミットに失敗する問題の修正

.github/workflows/build.yml
見逃す恐れがあるためすべてチェックする
PR https://github.com/npocccties/chibichilo/pull/813 を見ていてCIの自動チェックからPRの変更に含まれないファイルが漏れていたのでそれを含めます。
参考文献: https://github.com/marketplace/actions/eslint-annotate-from-report-json
=> chore: PRの変更に含まれないファイルのLintエラーもチェックする

server/tests/wowzaUploadTest.ts, server/utils/zoom/import.ts
ref #798
確認したこと:
- 大きいファイルの書き込みにBufferを使用してる箇所をStreamに
- WOWZA_SCP_* 環境変数を設定して `node -r esbuild-register server/tests/wowzaUploadTest.ts`
- SSHでの転送時のサイズ制限に関しては問題無いことを確認
=> fix: Bufferのサイズ制限を回避するためにStreamを使う

components/atoms/BookChip.stories.tsx, components/atoms/BookChip.tsx, components/organisms/ContentPreview.tsx, components/organisms/FilterColumn.tsx, components/templates/Topics.tsx, samples/index.ts, samples/relatedBook.ts, server/models/topic.ts, store/search.ts
関連 #779 #766 #806
トピック検索apiのブックでの絞り込みのクライアントの対応です。
=> feat: トピック一覧のブックでの絞り込み

pages/courses/index.tsx, store/book.ts, utils/useDialogProps.ts
ref #808
- アンマウント時にbookAtomをクリアすることでVideoJSプレイヤーへの副作用が残り続ける問題を防ぐ
- プレビュー用のコンポーネントを分割しプレビューが切り替わる際の副作用が残り続ける問題を防ぐ
=> fix: リンク一覧画面のプレビュー表示プロセスの修正

components/organisms/Video/VideoPlayer.tsx, components/organisms/Video/VideoResource.tsx, components/organisms/Video/index.tsx, utils/video/getVideoInstance.ts
ref #808
誤ってバックグラウドで再生されうる問題を防ぐ目的でインスタンス生成時の自動再生オプションを無効化しVideoPlayerコンポーネントで一貫して管理する
=> fix: プレイヤーオブジェクト生成時の自動再生プロセスの修正

components/organisms/Video/VideoPlayer.tsx, components/organisms/Video/index.tsx, store/video.ts
ref #808
- fix: プリロードする際に動画プレイヤーオブジェクトがすでに存在する場合インスタンスを生成しない
- fix: 自動再生プロセスの修正
プリロードする際に動画プレイヤーオブジェクトが存在しているかどうかに関わらず複数登録される問題の修正
アンマウント時に動画プレイヤーオブジェクトプールを初期化されるようにして次回マウント時には新しいインスタンスを生成する処理に変更
関数名を `updateVideo` → `preloadVideo` に変更
今後もMapへの副作用をstoreで扱うのが妥当かどうかは分からないがひとまずそのまま
また #835 の影響でonEnded, onDurationChange, onTimeUpdate の変更のタイミングで誤って自動再生が行われる問題があった
その修正
=> fix: プリロードする際に動画プレイヤーオブジェクトがすでに存在する場合インスタンスを生成しないように修正

components/organisms/BookForm.tsx
ref #839
AM/PM含めず12時間表記 (`hh`)を使っていた
https://date-fns.org/v2.29.1/docs/format
その修正
=> fix: `HH` (例: 00, 01, 02, ..., 23) を使う

utils/book.ts
ref gh-829
8ceb0ea02ccc6a49610c5c6d6f0611a64d176b37 でuseSWRImmutableに変更した影響で変更内容が反映されない不具合があった。
その修正。
=> fix: コンポーネントをマウントした時に自動的に再検証することで変更内容が反映されない問題を防ぐ

components/organisms/Video/index.tsx
ref #840
ビデオプレイヤーオブジェクトプールの変更検知が機能せずendedイベントハンドラーが注入されずトピックの切り替えが行われない不具合があった。
endedイベントハンドラーに関してもVideoPlayerコンポーネントで一貫して管理するように変更を行う。
=> fix: トピックの切り替えが行われない不具合の修正

INSTALL-en.md, INSTALL-ja.md, docker-compose.yml, package.json, server/package.json, yarn.lock
- openid-client 5.1.8 → 5.2.1 更新
- `node:18.12-alpine3.16` イメージ へのアップデート
=> chore: 依存関係の更新 (Node.js v18 対応)

components/organisms/Video/VideoPlayer.tsx, components/organisms/Video/index.tsx, store/video.ts
ref #840
- セクションが切り替わったことを検知する目的でonEndedの変更検知に応じた自動再生処理の追加
- バックグラウンドで動画プレイヤーオブジェクトプールの初期化プロセスを変更
=> fix: ブックプレビューでトピックを切り替えると自動再生されないことがある問題の修正

compose.yml, moodle/Dockerfile
fixed https://github.com/npocccties/chibichilo/issues/820
この変更でvolumesに永続化されるのでdocker compose down && docker compose up -dしても元の環境に復帰できるようになります。
(もし初期化したい場合は適宜 docker volume rm コマンドを使用するようにしてください) 
volumes
- mariadb_data_v10: mariadb サービスの /var/lib/mysql の volume
- moodle_data_v4: moodle サービスの /bitnami/moodle の volume
- moodledata_data_v4: moodle サービスの /bitnami/moodledata の volume
- postgres_data_v15: db サービスの /var/lib/postgresql/data の voume
加えて https://github.com/npocccties/chibichilo/issues/797 の AH00023問題に関する修正を moodle/Dockerfile にて含めています。
=> fix: 開発用データの外部化

components/molecules/CourseSearchTextField.tsx, components/templates/Courses.tsx, server/models/link/searchQuery.ts, server/utils/linkSearch/linkSearch.ts, server/utils/linkSearch/parser.test.ts, server/utils/linkSearch/parser.ts, store/linkSearch.ts, types/linkSearchTarget.ts
ref:[#788](https://github.com/npocccties/chibichilo/issues/788)
UIは以下のようにブック検索などと揃えました。
以下の項目で検索できる
- コース名
- リンクのタイトル
- ブック名
- トピック名
以下の絞り込み検索ができる
- リンクタイトル
- ブック
- トピック
=> feat:ブック・トピック・LTIリンク・コースのタイトルから検索する

components/atoms/SortLinkSelect.stories.tsx, components/atoms/SortLinkSelect.tsx, components/templates/Courses.tsx, server/models/sortLinkOrder.ts, server/utils/linkSearch/linkSearch.ts, server/utils/makeSortLinkOrderQuery.ts, server/validators/linkSearchProps.ts, store/linkSearch.ts, utils/courses/useLinks.ts
関連：#789
項目はブックなどと合わせて、以下のように
- 更新日時
- 作成日時
- タイトル
でのソートを追加しました。
=> feat:LTIリンクのソート項目を増やす

components/organisms/Video/VideoPlayer.tsx
ref. https://github.com/npocccties/chibichilo/issues/851
videojs-youtube において再生されない不具合があるので play イベントが発火されなければ再実行を試みるように変更します
=> fix: YouTube 動画の自動再生しない問題の修正

server/utils/book/updateBook.ts, server/utils/topic/upsertTopic.ts
ref #673
複数のトピックや複数のブックに同じキーワードが設定されているとき更新前のキーワードの取得処理が機能せず期待通り削除されない不具合があった。更新前のキーワードの取得処理を修正しキーワードを削除できるように修正します。
=> fix: キーワードが削除されない不具合の修正

components/organisms/BookInfo.tsx, components/organisms/Sections.stories.tsx, components/organisms/Video/index.tsx, components/templates/Book.tsx
ブック詳細/トピック詳細/タイムライン周りのデザイン更新
https://github.com/npocccties/chibichilo/issues/876
のブック詳細部分の修正です。
- ブック詳細の学習時間は外に出し，見た目もトピック学習時間と同じにする
- ブック詳細にある「教材の主要な言語」は消す
- ブック詳細に「キーワード」を追加する
=> feat:ブック詳細のデザイン更新

components/organisms/TopicViewerContent.tsx, components/organisms/Video/index.tsx
ブック詳細/トピック詳細/タイムライン周りのデザイン更新
https://github.com/npocccties/chibichilo/issues/876
のトピック詳細部分の修正です。
- トピック詳細に「キーワード」を追加する
- トピックエリアは，Tab UIパターンで | 解説 | 視聴時間詳細 | トピックの詳細 |で切り替えるようにする
=> feat:トピック詳細/タイムライン周りのデザイン更新

components/organisms/BookForm.tsx, components/templates/BookEdit.tsx, components/templates/ReleaseEdit.tsx, pages/book/edit/index.tsx, pages/book/release/index.tsx, utils/book.ts
ref #887 
以下の作業を行いました。
- ブック編集画面にリリースボタンを追加する (#885 残作業)
- リリース画面の作成
- リリース済みブックを ReleasedBook で表示する
フォークボタンは console.log するだけです。
リリース画面や ReleasedBook に「戻る」ボタンがないのが気になっています。
=> feat: リリース画面の実装

components/organisms/BookForm.tsx, components/templates/BookEdit.stories.tsx, components/templates/BookEdit.tsx, components/templates/BookNew.tsx, components/templates/ReleasedBook.tsx, pages/book/edit/index.tsx, utils/useBookLinkHandler.ts, utils/useBookNewHandlers.ts
ブックの編集画面とリリース画面でのボタンの配置を変更します。
リリース画面: 「コースへの提供」ボタンを配置しました
ブック編集画面: 「コースへ提供」ボタンをフォームの外に配置してリリースボタンなどと並ぶように調整しました
スクリーンショット
Before: コースに提供すると「コースへ提供」ボタンが非表示になる都合で狭く配置される
After
リリース画面:
ブック編集画面:
=> ブック編集画面/リリース画面でのボタンの配置

components/organisms/TopicViewerContent.tsx, components/organisms/Video/index.tsx
#921 の修正です。
ずれてしまうのは、空のVideoJSPlayerが生成されてしまうことが原因でした。
非表示の要素を表示しないことで修正しました。
以下のようなwarningが出てしまうので要対応ですが、動作に問題ないことを確認しました。
```
YouTube player is not attached to the DOM. API calls should be made after the onReady event. See more: https://developers.google.com/youtube/iframe_api_reference#Events 
```
=> fix:配信中ブックのビデオや解説エリアがトピック数に応じてずれる

components/templates/BookTreeDiagram.tsx
ref #902
バージョンツリー画面でフォーク数を表示します。
久しぶりに再帰呼び出しを使いました。
リーフノードの「フォーク数:0」は表示しなくても良いかも知れません。
=> フォーク数を表示する

server/services/book/fork/create.ts, server/utils/book/bookToBookSchema.ts
変更点
- sectionIdフィールドが含まれフォークに失敗する問題を修正
- 自身の著作のブック以外のフォークを許容
型に存在しないフィールドが含まれていました。
server/utils/book/bookToBookSchema.ts:R101
```
...topicSection,
```
ここでTopicに存在していないTopicSectionのフィールドを追加している処理がありました。
それを削除して修正しました。
(6bc5c18 [3年前のコミット](https://github.com/npocccties/chibichilo/blob/6bc5c180ffa6853a77663a2ef4ecb18e99ef8a9a/server/utils/user.ts#L89)でTopicSchemaとしては本来含めてはいけない意図していないフィールドが含まれている、 https://github.com/npocccties/chibichilo/compare/9fec5d32fcc583412b0d62bcaacb00e98aad28a4..0f9ca43aa3139278f0741fadfbb2f72989f94080 での変更漏れ)
また、自身の著者のブック以外でフォークが許可されていませんでした。
ほかの教員のブックに関してもフォークを許可します。
=> フォークできない問題の修正

server/config/seeds/books.ts, server/utils/keyword/keywordsConnectOrCreateInput.ts
キーワードが設定されているときフォークに失敗する不具合がありました。
キーワード作成処理実行時のフィールドを厳格にすることによってその問題を修正します。
=> fix: キーワードが設定されているときフォークに失敗する不具合を修正

components/organisms/BookTreeDialog.tsx, components/templates/BookTreeDiagram.tsx, pages/book/tree/index.tsx
ref #892 
ツリー画面に拡大、縮小、リセットボタンを追加しました。
- zoom パラメータの初期値は 1.0
- 1.0以上に拡大することはできない
- 拡大は zoom を 1.1倍
- 縮小は zoom を 1.1で割る
- リセットすると zoom が 1.0 に戻る
- zoom パラメータが変化すると、ツリーの表示位置はリセットされる
=> ツリー画面に拡大、縮小、リセットボタンを追加

components/organisms/BookTreeDialog.tsx, components/templates/BookTreeDiagram.tsx, openapi/apis/DefaultApi.ts, openapi/models/InlineResponse2008Nodes.ts, pages/book/tree/index.tsx, server/models/book/tree.ts, server/utils/book/findTree.ts
ref #893 
バージョンツリー画面でシェアしていないブックと削除済みブックの表示方法を変更しました。
- /api/v2/book/{book_id}/tree が返すブック毎の TreeNodeSchema に shared を追加しました
- 円を点線で表示し、削除済みは少し薄いグレーにしています。
- `クリックすると、「シェアしていないブック」「削除されたブック」と表示します
=> シェアしていないブックを表示しない

components/organisms/BookTreeDialog.tsx, components/organisms/VersionTreeDialog.tsx, pages/book/edit/index.tsx
ref #893
バージョンツリーをオーバレイ表示するように変更しました。
components/organisms/VersionTreeDialog.tsx を作成し pages/book/edit/index.tsx を変更しています。
pages/book/tree/index.tsx, utils/useBookEditHandlers.ts onBookTreeButtonClick 関数
は使用しなくなりましたが、まだ削除していません。
components/templates/BookTreeDiagram.tsx, components/organisms/BookTreeDialog.tsx は、BookTree -> VersionTree に改名、templates -> organisms へ移動したほうが良さそうですが、まだ作業していません。
=> バージョンツリーをオーバレイ表示する

pages/book/edit/index.tsx, pages/book/import/index.tsx, pages/book/release/index.tsx, pages/book/topic/import/index.tsx, pages/book/tree/index.tsx, pages/topics/edit.tsx
(https://github.com/npocccties/chibichilo/pull/949 と同じ)
ブックが存在しないとき「トピックが見つかりませんでした」と表示される不具合がありました。
それを修正します。
=> fix: ブックが存在しないとき「トピックが見つかりませんでした」と表示される不具合を修正

components/templates/BookTreeDiagram.tsx
ref #893 
onUpdate イベントでツリーの現在位置を把握し、
拡大、縮小時にツリーの現在位置をリセットしないようにしました。
これまでは、ツリーを移動したあと拡大、縮小すると、
ツリーの位置がデフォルトに戻っていました。
リセットボタンを押すと、zoom パラメータ 1.0 で、デフォルト位置に戻ります。
=> 拡大縮小で位置をリセットしない

components/organisms/ContentPreview.tsx, components/organisms/ReleasedBookCard.tsx, components/templates/Book.tsx, components/templates/ReleasedBook.tsx
ref https://github.com/npocccties/chibichilo/issues/927
リリース済みであることをより分かりやすくします。
またリリースバージョンなどの情報の近くに編集ボタンを配置し、意味的に近い部分に配置することによってより分かりやすくします。
スクリーンショット
バージョン・リリース日の表示
リリース編集ボタン
=> feat: リリース済みのブックに関してはバージョン・リリース日を表示

components/templates/Book.tsx
ref #929
学習時間が0のときfalseではなくnumberのまま扱われ表示される不具合がありました。
0の場合も同じデザインにすることによってその不具合を回避します。
=> fix: 学習時間 "0" が表示される不具合の修正

server/services/init.ts, server/utils/ltiResourceLink.ts
resolved #967 resolved #968
- feat: Target Link URI をもとに LTI Resource Link として紐付ける
確認したこと: Tool URL を変更し LTI Resource Link によって提供されるブックが変更可能なこと
その提供されているブックにリダイレクトされること
[Screencast from 2023年07月11日 18時56分46秒.webm](https://github.com/npocccties/chibichilo/assets/1730234/ccdbc791-74ae-4699-be0a-e3be2e93fe48)
http://localhost:3000/book?bookId=1 → http://localhost:3000/book?bookId=2 に変更出来ることを確認
また、従来どおり操作できることを一通り確認
=> feat: Target Link URI をもとに LTI Resource Link として紐付ける

components/organisms/AppBar.tsx, components/organisms/ContentPreview.tsx, components/templates/Books.tsx, pages/books/index.tsx
操作の廃止は以前仮実装を行いました。
関連：#973
issue: #970
このPRでは、実際にセッションの値を見て、Deep Linkか否かを判定し、いつくかの操作を廃止する対応を行いました。
=> feat:UI: Deep Linking でのリンクの選択画面でのいくつかの操作の廃止

components/organisms/Video/index.tsx, server/models/event.ts, utils/eventLogger/logger.ts, utils/eventLogger/playerTracker.ts
fixed #985
Video.js v8でのfirstplayイベントの削除に起因して発生するようになっていた再生開始位置の設定機能の不具合を修正します。
=> fix: 再生開始位置の設定が反映されない不具合の修正

components/organisms/Video/index.tsx, types/videoInstance.ts, utils/video/getVideoInstance.ts
ref #986
#986 変更によって動画プレイヤーコンポーネントがマウントされるたびに初回再生用のハンドラーが注入される問題がありました。動画プレイヤーオブジェクトごとに1度しか呼ばれないように抑制します。
=> fix: 2回目以降も再生開始位置の設定が反映される不具合の修正

server/package.json, server/utils/book/importBooksUtil.ts, yarn.lock
ref #925
unzipper を最新の 0.10.14 に更新してみましたが、動作は変わりませんでした。
unzipper の Extract ではなく Parse を使って自分でファイルを書くと問題が発生しません。
=> fix: node 18.16.0 以降で発生する unzipper の誤動作対策

components/templates/BookEdit.tsx, components/templates/BookNew.tsx, components/templates/Books.tsx, pages/book/edit/index.tsx, pages/book/index.tsx, server/services/init.ts, utils/useBookLinkingHandlers.ts, utils/useBookNewHandlers.ts
resolved #969
- Tool URL (target\_link\_uri) が設定されている場合、リンクの変更を禁止
確認したこと
- 従来どおり操作できること
- DL設定後、ブック一覧画面、閲覧、作成、編集画面でリンクの変更のためのボタンが表示されないこと
=> Tool URL (target_link_uri) が設定されている場合、リンクの変更を禁止

components/organisms/Video/index.tsx, utils/eventLogger/logger.ts, utils/eventLogger/playerTracker.ts
resolved #995 
この変更によって初回・トピック切り替えのタイミングで発火していたplayイベントについて、新たに"first"を付与します。
確認方法:
1. `yarn dev | grep 'play.*videoplayerlog'` コマンドで開発用サーバーを起動
2. 学習者がアクセスする
3. 操作をしながらログを確認
[Screencast from 2023年08月29日 15時56分21秒.webm](https://github.com/npocccties/chibichilo/assets/1730234/0c481464-1784-4e2c-8e51-08c294952b84)
=> feat: 視聴ログ: 初回再生時であることを判定するためのplayイベントの拡張

components/organisms/BookForm.tsx, components/templates/BookEdit.tsx, components/templates/BookNew.tsx
ref #999 https://github.com/npocccties/chibichilo/pull/980#issuecomment-1716764109
- ブック作成・編集での「コースへ提供」チェックボックスに関して、従来どおり表示しつつツールURLが指定されている場合は無効化するように変更します
- ただし、チェックボックスをトグルスイッチのようにするといった変更は本PRには含めず別途とさせてください
=> ブック作成・編集でのリンク切り替えの説明をtitle属性に追加/ツールURL指定時無効化

server/services/bookImport.ts, server/services/topicImport.ts, server/utils/book/importBooksUtil.ts
以下の 2つの issue に対応します。
- #994 
- #1001
同じファイル server/utils/book/importBooksUtil.ts を変更するため、ひとつのプルリクにしています。
#994 の経緯は次のとおりです。
- #990 に対応するためにコードを変更したところ、階層ディレクトリを含む zip ファイルを解凍することができなくなった
- unzip 以外の部分のコードは、もともと階層ディレクトリを含む zip ファイルに対応していた
ブックを上書きインポートするとき、自身の著作でないトピックが含まれている場合は、次のようなメッセージが表示されます。
=> 上書きインポート機能の改良

server/services/session.ts
session バリデーションのチェックに失敗するケースが存在しました。それを修正します。
これによって公開しているブックにアクセスしているとき GET /api/v2/session で 500 エラーになる問題を解決します。
fixed npocccties/chibichilo#1003
=> fix: 公開している提供中ブック視聴途中でブックが最初から再生される問題の修正

server/utils/user.ts
resolved #1005
upsertUserの内部でuser.name, emailが空(undefined, null, "")のとき上書きしないように変更しました。
=> fix: name, emailが空のとき上書きしないように変更

utils/video/getVideoJsPlayer.ts
fixed #860
nativeTextTracksが有効化されている環境でブラウザネイティブの字幕(テキストトラック)を追加すると、mp3音声対応のために導入しているvideojs-hlsjs-pluginの内部処理と競合して動画に設定した字幕の選択肢が複数表示される問題がありました。
Video.jsのオプションhtml5.nativeTextTracksを無効化しVideo.jsによってエミュレートされるテキストトラック使用することによってこの問題を回避します。
https://videojs.com/guides/text-tracks/#emulated-text-tracks
- Wowza
- mp3を含むHLS
- Video.js 8
- videojs-hlsjs-plugin
- Windows10+ or macOS Monterey+
- Wowzaを対象にした場合、問題が発生することがあることを手元の環境でも確認  (確認した動画は HLS/mp3 )
- player.addRemoteTextTrack() メソッドの呼び出しは通常通り1度しか行われていない
- components/organisms/Video/VideoJs.tsx:L61
- トレースしていくと Video.js 内部では addRemoteTextTrack() が余計に1度多く呼び出されることがある
- `@meikidd/videojs-hlsjs-plugin`
- https://github.com/meikidd/videojs-hlsjs-plugin/blob/master/lib/videojs-hlsjs-plugin.js#L298-L318
変更後 `TextTrack.mode` …
=> fix: 動画に設定した字幕の選択肢が複数表示される問題の修正

server/package.json, server/utils/book/importBooksUtil.ts, yarn.lock
一括登録で zip ファイルを展開するときに使用するライブラリを unzipper から yauzl に変更します。
node v18.18.2 で CC server を動作させ、サンプル zip ファイルでの正常ケースと、いくつかの異常ケースでの動作を確認しています。
@ties-makimura いろんな zip ファイルでテストしてみていただけますでしょうか。すでにクローズされていますが、間違えて RCOSDP/GakuNinLMS-LTI-MC にプルリクを出してしまいました。申し訳ありません。
ref #1026
=> unzipperの替わりにyauzlを使用する

components/organisms/AuthorsInput.tsx, components/organisms/ContentPreview.tsx, components/organisms/TopicForm.tsx, components/organisms/TopicForm/TimeRequiredInputControl.tsx, components/templates/BookEdit.stories.tsx, components/templates/BookEditReleased.stories.tsx, components/templates/TopicEdit.tsx, openapi/models/InlineResponse2005RelatedBooks.ts, server/models/book/release.ts, server/models/topic.ts, utils/release.ts
トピック編集画面で、編集中/リリース済みトピックを区別して表示します。
リリースモード開発_機能整理.xlsx の、機能63-77 に対応します。
変更点の詳細については、次回 9月17日のアジェンダ https://github.com/npocccties/chibichilo-db-refactoring/issues/29
に記載予定です。
記録用のプルリクなので、すぐ feat-vm2 にマージします。
=> 2024年 版管理 9月14日バージョン

components/atoms/AuthorFilter.tsx, server/models/authorFilter.ts, server/utils/search/bookSearch.ts, server/utils/search/createScopes.ts, server/utils/search/topicSearch.ts, server/validators/searchProps.ts
以下の機能の実装です。
- [機能4] ブック一覧 編集中／リリース条件の絞り込み
- [機能55] トピック一覧 編集中／リリース条件の絞り込み
既存機能と動作を比べることができるよう、次のようにしています。
- 既存の絞り込み機能に、[編集中] [リリース] [他人のリリース]を追加した
- [自分] [自分以外] [共有あり/なし/すべて] は UI を削除する予定
- [すべて]は残してもよいかも
管理用のプルリクなので、すぐ feat-vm2 ブランチにマージします。
=> 編集中／リリース条件の絞り込み の試作

components/atoms/AuthorFilter.tsx, components/organisms/FilterColumn.tsx, store/search.ts
ボタンを削減しました。
「他人のリリース」は「共有されたリリース」に変更しました。
ブック一覧の絞り込み条件で、ライセンスを指定できるようにしました。
デフォルトで [編集中] コンテンツが表示されます。
=> ブック、トピック一覧の絞り込み機能を変更

components/molecules/SectionsTree.tsx, components/organisms/ReleaseItemList.tsx, components/templates/ReleaseEdit.tsx, components/templates/Topics.tsx, openapi/apis/DefaultApi.ts, openapi/models/InlineObject6.ts, openapi/models/InlineObject7.ts, openapi/models/InlineResponse2005Release.ts, pages/book/edit/index.tsx, pages/book/release/index.tsx, server/models/book/release.ts, server/services/book/release/create.ts, server/services/book/release/update.ts, server/utils/book/cloneBook.ts
ブックをリリースするときに、トピックを選択できるようにしました。
- API 変更 (トピックのリストを受け取る)
- サーバ側動作の変更
- トピックを選択するUIの実装
他に、UI の動作を以下のように変更しています。
- リリース画面: リリース後遷移したブック編集画面から戻る context が未設定だった
- ブック編集画面 -> リリース画面 -> ブック編集画面で context=books を保存
- トピック一覧で、トピックを選んでも[ブック作成]だけが表示される
- 絞り込み条件によって表示するボタンを変えている
- 仕様は暫定的
```
これまで      版管理
---------------------------------------------------------------
ブック作成  常時          admin,edit
シェア      admin,self    admin,release
シェア解除  admin,self    admin,release
削除        admin,self    admin,edit,release
```
=> リリース時にトピックを選択する

components/organisms/BookForm.tsx, components/templates/BookEdit.stories.tsx, components/templates/BookEdit.tsx, components/templates/BookEditReleased.stories.tsx, components/templates/BookEditReleased.tsx, components/templates/Books.tsx, openapi/apis/DefaultApi.ts, pages/book/edit/index.tsx, server/config/routes/book.ts, server/services/book/index.ts, server/services/book/release/create.ts, server/services/book/update.ts, server/services/clone.ts, server/utils/book/cloneBook.ts, server/utils/book/cloneSections.ts, server/utils/book/createBook.ts, server/utils/book/updateBook.ts, server/utils/topic/cloneTopic.ts, server/utils/uniqueId.ts, server/validators/bookQuery.ts, utils/book.ts
以下のケースで、再利用するトピックを複製する機能を実装した。
- ブックの複製
- ブックへのトピックの追加
- トピック一覧からブック作成
いくつか課題が残っていて、テストも充分とはいえないが、現状のコードを feat-vm2 ブランチにマージする。
=> (ウ,エ,カ) 「複製」の追加、フォークの廃止、再利用の廃止

server/services/book/release/show.ts, server/services/clone.ts, server/utils/displayableBook.ts
https://github.com/npocccties/chibichilo-db-refactoring/issues/58
で課題になっていた、以下の件について対応しました。
- ブックの複製
- 共有されたリリースのリリース一覧が取得できない
- 共有されたリリースのブックが複製できない
- (オ)シェア廃止 に伴うブック編集ページでのトピック表示問題
ブックの複製については、予定どおり、共有リリースのブックに対する API の使用を許可するように変更しました。
トピック表示問題については、「(変更案2)見えるブックに含まれるトピックは見えることにする」を実装しました。
このプルリクは、すぐ feat-vm2 にマージします。
=> ブックの複製、シェア廃止に伴うトピック表示問題の改良

openapi/apis/DefaultApi.ts, openapi/models/InlineResponse2005Release.ts, server/models/book/release.ts, server/prisma/seed.ts, server/services/book/create.ts, server/services/book/release/create.ts, server/services/clone.ts, server/utils/book/cloneBook.ts, server/utils/book/createBook.ts, server/utils/book/updateBook.ts
feat-vm2 ブランチを、以下のように変更しました。
- リリースとブックの複製でトピックを 2回複製していたのを 1回だけにした
- 元ブック+複製トピックをリリース、複製ブック+元トピックを編集中にする
- ReleaseSchema の不要な topics を削除
- server/prisma/seed.ts で createBook 呼び出しの引数を追加
このプルリクは、すぐに feat-vm2 ブランチにマージします。
=> feat-vm2 の修正

components/templates/Topics.tsx, pages/topics/index.tsx
トピック一覧画面の動作を以下のように変更しました。
- 絞り込みでリリースを選択しているとき、削除ボタンを表示しない
- 削除ボタンを押したとき、リリースしたブックに含まれるトピックを削除しない
このプルリクは、すぐに feat-vm2 ブランチにマージします。
=> fix: リリースしているトピックを削除しない

server/utils/search/createScopes.ts, server/utils/uniqueId.ts
リリースで複製した他人のトピックが、トピック一覧に表示されるように修正しました。
詳細は、https://github.com/npocccties/chibichilo-db-refactoring/issues/63#issuecomment-2590043112 に記載しています。
=> fix: リリースで複製した他人のトピックが、トピック一覧に表示されない

components/organisms/BookForm.tsx, components/organisms/BookInfo.tsx, components/organisms/ContentPreview.tsx, components/organisms/Video/index.tsx, components/templates/Book.tsx, pages/book/index.tsx, server/services/book/release/show.ts, server/utils/book/release.ts, utils/useParentBookInfo.ts
視聴画面 ブック詳細で、親ブック情報を表示するように変更しました。
また、以下の場所で "著作権者" を表示するようにしました。
- ブック視聴画面
- ブック一覧画面
- トピックの詳細
=> 新シナリオ対応: 学習者が親追跡できる

components/templates/Book.tsx, server/services/book/release/show.ts, server/utils/book/release.ts
リリース一覧API で管理者に対応しました。
以下の点が修正されています。
- 管理者がブック視聴画面で直前のリリース情報を見ることができる
- 管理者がブック編集画面で他人のブックのリリース一覧を見ることができる
また、視聴画面 ブックのライセンスロゴを学習時間の右に表示するようにしました。
=> 管理者がブック視聴画面で直前のリリース情報を見ることができる 他

components/templates/Book.tsx
学習時間の右側に表示したCCライセンスのロゴをクリックすると、
CC公式のライセンスページに移動するように変更しました。
=> fix: ブックのCCロゴから公式ページに移動する

openapi/models/InlineResponse20014BookActivities.ts, openapi/models/InlineResponse2008Activity.ts, openapi/models/InlineResponse2008Learner.ts, server/models/activity.ts, server/models/learner.ts, server/utils/activity/findAllActivity.ts, utils/bookLearningActivity/getLocaleEntries.ts
resolved: #1064
学習分析データの項目を以下の通りとする。
（以下の1~4が新規追加分）
**1. LMSのクライアントID(LtiConsumer.id)（追加）
2. LMSのコースID (LtiContext.id)（追加）
3. LMSのコース名 (LtiContext.title)（追加）
4. LMSのユーザID(User.ltiUserId)（追加）**
5. ユーザID（既存）
6. ユーザ名（既存）
7. メールアドレス（既存）
8. ブックID（既存）
9. ブック名（既存）
10. トピックID（既存）
11. トピック名（既存）
12. 動画の長さ（既存）
13. ユニーク視聴時間（既存）
14. 学習状況（既存）
15. 学習完了率（既存）
16. 初回アクセス（既存）
17. 最終アクセス（既存）
影響範囲は以下の2箇所。
- 学習者タブのマウスオーバー時の吹き出し
- ![image](https://github.com/user-attachments/assets/0681a8e4-497e-43bd-841c-e76ada11bc15)
- 「視聴分析データをダウンロード」から入手できるCSVファイル
※ #1066 においても同様の「視聴分析データをダウンロード」形式となるようにする予定（本Issueは上の2つのみがスコープとする）
=> 学習分析データにLMS情報を追加

server/utils/activity/bookWithActivity.ts, server/utils/activity/findAllActivity.ts, utils/getActivitiesByBooks.ts
resolved: #1065 
学習分析・ダウンロードページの視聴分析データに未視聴者（未開封）の学習者のデータが含まれるようになりました。
=> 学習分析・ダウンロードページのCSVに未視聴データを追加

components/templates/BookEdit.tsx
(課題1) トピックが複数のブックに含まれるとき の対応として、以下のように変更します。
- リリース時に、トピックの作成者がブックの作成者であることをチェックする
- ブックの作成者でない作成者のトピックが一つ以上ある場合は、リリース不可とする
- リリース不可の場合、UI でリリースボタンを押したときに以下のメッセージを表示する
=> リリースでトピックの作成者がブックの作成者であることをチェックする

server/utils/displayableBook.ts
https://github.com/npocccties/ChibiCHiLO-private/issues/312#issuecomment-2809699645 の手順で、Aだけが作成者のブックに Bだけが作成者のトピックが含まれる状態を作ったとき、Aがブックをリリースできてしまう問題に対処します。
server/utils/displayableBook.ts の関数 getDisplayableBook がtopic.shared を参照していて、次のように動作していました。
- topic.shared == true  -> 作成者によらず topic を book に含める
- topic.shared == false -> 作成者が同じときだけ topic を book に含める
Dec 27, 2024 に以下の変更を行なっています。
fix: シェア廃止 見えるブックに含まれるトピックはすべて見える
https://github.com/npocccties/chibichilo/commit/52b5d6c102c5365ab690f19961db5504cefe0954
Arp 5, 2025 に chibichilo feat-vm2 に master を merge したとき、以下のcommit と CONFLICT したのですが、私が CONFLICT を解消するときに間違ったようです。
fix: ダウンロードページでの表示可能ブックが教員向けになっていなかった
https://github.com/npocccties/chibichilo/commit/acda2fec1ba89d7b8e4f1772af3c394ca739e32a
master を merge した作業全体を見直して、このプルリク以外の変更は必要ないと判断しました。
=> fix: すべてのトピックが見える

components/organisms/ReleaseItemList.stories.tsx, components/organisms/ReleaseItemList.tsx, components/templates/BookEdit.tsx, components/templates/BookEditReleased.tsx, components/templates/TopicEdit.tsx, server/services/topic/release/show.ts, server/utils/book/release.ts, server/utils/topic/release.ts
- 以下のページで表示するリリース一覧で関連するブック/トピックを表示する
- ブックの編集
- トピックの編集
- 表示内容(表示順)
- 編集中 (oid が同じ系統で編集中、0,1個)
- リリース (oid が同じ系統、リリース日の降順、0,1,複数)
- 複製元 (同系統の最も古いリリースのpidをvidとして持つ直接の親、0,1個)
- 複製先 (vidをpidとしてもつ、oid が異なる、0,1,複数)
- 表示されるブック/トピック
- ブック/トピック一覧に表示されるものだけ
- 他人が複製した編集中のブック/トピックは、リリース一覧に表示されない
- リリースして共有されると「複製先」として表示される
- 「複製先」の「複製先」は表示されない
- 「複製先」のブック/トピックの編集画面に表示される
動作確認を実施して feat-vm2 にマージする。
=> リリースの編集中の親が分かる

components/organisms/Video/index.tsx
topic.descriptionに長いURLが含まれる際のレイアウト崩れを修正
=> fix: markdown内の長いURLの改行問題を解決

components/atoms/AuthorFilter.tsx, components/molecules/SectionsTree.tsx, openapi/apis/DefaultApi.ts, server/models/authorFilter.ts, server/models/booksImportParams.ts, server/utils/book/cloneBook.ts, server/utils/search/createScopes.ts, server/utils/topic/cloneTopic.ts, server/validators/searchProps.ts
以下の変更を行います。
- ブック/トピック一覧の絞り込みで、"共有されたリリース" を "リリース(共有)" に変更
- "リリース(共有)" に自分のブック/トピックも表示する
- ブック編集画面、トピックツリー表示でシェアマークを表示しない
- 一括登録でブック/トピックの shared を false にする
- トピックの再利用、リリース、ブックの複製でブック/トピックを複製するとき shared を false にする
=> UI: リリース(共有)、シェア廃止関連

components/organisms/ReleaseItemList.tsx, openapi/models/InlineResponse20010Releases.ts, server/models/book.ts, server/models/releaseResult.ts, server/models/topic.ts, server/prisma/migrations/20250429124949_add_spid/migration.sql, server/prisma/schema.prisma, server/utils/book/destroyBook.ts, server/utils/topic/destroyTopic.ts, server/utils/uniqueId.ts
model Book, Topic に spid を追加し、履歴途中のコンテンツが削除された場合も、履歴を追うことができるようにしました。アルゴリズムの概要は次のとおりです。
- ユニークID spid に直前リリースの vid を覚える
- 新規作成時 pid と同じ内容を設定
- リリースは、リリース前の spid を保持
- 複製には、複製元の vid を設定
- 削除時は、削除対象の vid を pid または spid に持つすべてを更新する
- 更新対象の spid を、削除対象の spid で書き換える
- 削除対象の spid が空の場合は pid を使用する
リリース一覧表示も、次のように変更しています。
- 複製元を探すとき spid を使用する
- 複製先を探すとき spid を使用する
- リリースしていない編集中コンテンツの複製元を、リリース一覧に表示する
=> 履歴途中のコンテンツが削除されても履歴が追える

components/organisms/ReleaseForm.tsx, components/organisms/ReleaseItemList.stories.tsx, components/organisms/ReleaseItemList.tsx, components/templates/BookEdit.tsx, components/templates/BookEditReleased.tsx, components/templates/TopicEdit.tsx, pages/book/edit/index.tsx, server/utils/book/cloneSections.ts
2025年5月8日 打合せの課題について、調査と修正を行いました。すべての課題について、対処できたと考えています。
https://github.com/npocccties/chibichilo-db-refactoring/issues/74#issuecomment-2861999531
- 画面遷移の手順により，リリースの共有で、チェックが表示されないことがある
ブックの編集、トピックの編集を修正しました。
- リリース一覧の，リリースされたブックのえんぴつアイコンをマウスオーバーしたときに，「ブックを編集」と表示される
トピックの編集では、「トピックを編集」と表示するようにしました。
- リリース一覧からえんぴつアイコンをクリックしたときに，戻るボタンが表示され，行き先がブック閲覧画面となる
ブック編集画面のリリース一覧から別のブック編集画面に移動したとき、context を保存するようにしました。戻る先は、books か courses になります。
トピック編集画面の path は 2種類あって、それぞれ戻る先が違います。
```
path                  どこから         戻る先
-----------------------------------------------------
topics/edit           トピック一覧     トピック一覧
book/edit/topic/edit  ブック編集       元のブック編集
```
リリース一覧から別のトピックに移動したとき、path は topics/edit になり、戻る先はトピック一覧です。元のブック編集画面には戻りません。この動作は変更しませんでした。
- ブック編集画面の再利用ボタンの動作 …
=> 2025年5月8日 打合せの課題への対応

server/services/activityRewatchRate.ts, server/utils/activity/findAllActivityWithTimeRangeCount.ts, utils/useRewatchRate.ts
resolved: #1094 
issue中の画像のように、SWRの挙動としてAPIへの問い合わせを自動で行うので、それを制限してみました。
- すでにキャッシュがあれば更新しない
- ブラウザのタブがフォーカスされる度に更新することはしない
=> fix: 繰返視聴回数についてキャッシュデータの自動再検証を制限
